import * as THREE from 'three';
import {breakoutControls} from './breakout-controls.js';
import {createBreakoutState} from '../world/breakout-state.js';
import {nextBeatDelay} from './domain.js';
export function bindBreakout(section,main,{world,score,signal}){
 const model=world?.model,fallback=createBreakoutState(),frame=main.querySelector('.experiment-frame'),ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let ready=false,visible=false,owner='hero',epoch=0,pending=[],lastCue=-1;
 const state=()=>model?.state.state||fallback.state,post=data=>frame.contentWindow?.postMessage(data,location.origin);
 const eventCue=event=>{if(event.kind==='serve'||event.kind==='reset'){lastCue=-1;if(event.kind==='serve')score.cue('hover',event.wait||0);return;}if(event.kind==='won')score.cue('reveal');else if(['brick','paddle','miss'].includes(event.kind)&&event.time-lastCue>.06){lastCue=event.time;score.cue(event.kind==='brick'?'brick'+Math.floor(event.id/9):event.kind);}};
 const perform=(action,value)=>{if(owner==='transfer'){pending.push({action,value});pending=pending.slice(-8);return;}if(owner==='frame'){post({type:'breakout-action',epoch,action,value});return;}const target=model||fallback;if(action==='launch'){if(target.launch(value)){lastCue=-1;score.cue('hover',value.wait||0);}}if(action==='move')target.move(value);if(action==='aim')target.aim(value);if(action==='pause')target.pause(value);if(action==='reset'){target.reset();lastCue=-1;}controls.set(state());if(world)world.moving=1;};
 const launch=()=>perform('launch',{wait:score.audible?nextBeatDelay(score.time):0});
 const controls=breakoutControls({signal,onLaunch:launch,onMove:value=>perform('move',value),onAim:value=>perform('aim',value),onPause:value=>perform('pause',value),onReset:()=>perform('reset')});section.querySelector('.hero-note').remove();section.querySelector('.explore-button').before(controls.element);section.querySelector('.explore-button').textContent='带着这一局，靠近接着玩 ↓';main.querySelector('.experiment-intro p').textContent='同一张游戏台，同一局回弹。移动鼠标、拖动或用方向键接球；空格发球，P 暂停，R 重开。砖墙、分数和剩余机会会随你往返保留。';controls.set(state());
 if(!model){section.querySelector('.breakout-controls').hidden=true;section.querySelector('.explore-button').textContent='进入平面游戏台 ↓';}
 if(model){model.onState=controls.set;model.onEvent=eventCue;model.onPick=hit=>{perform('move',hit.x);if(state().status!=='playing')launch();};addEventListener('pointermove',event=>{if(event.pointerType==='touch'||event.target.closest('a,button,input'))return;const b=section.getBoundingClientRect();if(event.clientY<b.top||event.clientY>b.bottom)return;pointer.set(event.clientX/innerWidth*2-1,1-event.clientY/innerHeight*2);ray.setFromCamera(pointer,world.camera);const hit=model.pick(ray);if(hit)perform('move',hit.x);},{signal,passive:true});}
 const visibility=()=>{if(owner==='hero')model?.setActive(!document.hidden);if(!ready)return;const active=visible&&!document.hidden;if(active&&owner==='hero'){epoch++;owner='frame';model?.setActive(false);post({type:'breakout-owner',epoch,active:true,snapshot:model?.snapshot()||fallback.snapshot()});}else if(!active&&owner==='frame'){epoch++;owner='transfer';post({type:'breakout-owner',epoch,active:false});}};
 const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting&&entries[0].intersectionRatio>=.15;visibility();},{threshold:[0,.15]});observer.observe(frame);document.addEventListener('visibilitychange',visibility,{signal});
 addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==frame.contentWindow)return;const data=event.data;if(data?.type==='breakout-ready'){ready=true;visibility();}if(data?.type==='breakout-event'&&data.epoch===epoch&&owner==='frame')eventCue(data.event);
  if(data?.type==='breakout-settings'&&data.epoch===epoch&&owner==='frame'&&(model||fallback).restore(data.snapshot)){controls.set(state());if(world)world.moving=1;}
  if(data?.type==='breakout-state'&&data.epoch===epoch&&owner==='transfer'){(model||fallback).restore(data.snapshot);owner='hero';model?.setActive(!document.hidden);controls.set(state());if(world)world.moving=1;visibility();const actions=pending;pending=[];actions.forEach(({action,value})=>perform(action,value));}},{signal});
 signal.addEventListener('abort',()=>{observer.disconnect();post({type:'breakout-owner',epoch:++epoch,active:false});if(model)model.onState=model.onEvent=model.onPick=null;},{once:true});
}
