import * as THREE from 'three';
import {bulletControls} from './bullet-controls.js';
import {createBulletState} from '../world/bullet-state.js';
import {nextBeatDelay} from './domain.js';
export function bindBullet(section,main,{world,score,signal}){
 const model=world?.model,fallback=createBulletState(),frame=main.querySelector('.experiment-frame'),ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let ready=false,visible=false,owner='hero',epoch=0,pending=[],lastGraze=-100;
 const state=()=>model?.state.state||fallback.state,post=data=>frame.contentWindow?.postMessage(data,location.origin);
 const eventCue=e=>{if(e.kind==='start'||e.kind==='reset'){lastGraze=-100;if(e.kind==='start')score.cue('hover',e.wait||0);}else if(e.kind==='hit'){score.cue('hit');world?.actor.react();}else if(e.kind==='graze'&&e.tick-lastGraze>=12){lastGraze=e.tick;score.cue('graze');}else if(e.kind==='pattern')score.cue('hover');};
 const perform=(action,value)=>{if(owner==='transfer'){pending.push({action,value});pending=pending.slice(-8);return;}if(owner==='frame'){post({type:'bullet-action',epoch,action,value});return;}const target=model||fallback;if(action==='launch'&&target.launch(value))eventCue({kind:'start',wait:value.wait});if(action==='move')target.move(value.x,value.y);if(action==='pause')target.pause(value);if(action==='choose')target.choose(value);if(action==='reset'){target.reset();eventCue({kind:'reset'});}controls.set(state());if(world)world.moving=1;};
 const launch=()=>perform('launch',{wait:score.audible?nextBeatDelay(score.time):0});
 const controls=bulletControls({signal,onLaunch:launch,onPause:v=>perform('pause',v),onReset:()=>perform('reset'),onMove:(x,y)=>perform('move',{x,y}),onChoose:v=>perform('choose',v)});section.querySelector('.hero-note').remove();section.querySelector('.explore-button').before(controls.element);section.querySelector('.explore-button').textContent='带着这一刻，靠近继续 ↓';main.querySelector('.experiment-intro p').textContent='白点负责判定，外环提示擦弹；Mote 的身体不作判定。鼠标移动、手指相对拖动或方向键避让，Shift 微调，空格开始，P 暂停，R 重来。向下靠近与返回会保留同一局。';controls.set(state());
 if(!model){controls.element.hidden=true;section.querySelector('.explore-button').textContent='进入平面躲避场 ↓';}
 if(model){model.onState=controls.set;model.onEvent=eventCue;model.onPick=hit=>{perform('move',hit);if(state().status!=='playing')launch();};addEventListener('pointermove',event=>{if(event.pointerType==='touch'||event.target.closest('a,button,input,select'))return;const b=section.getBoundingClientRect();if(event.clientY<b.top||event.clientY>b.bottom)return;pointer.set(event.clientX/innerWidth*2-1,1-event.clientY/innerHeight*2);ray.setFromCamera(pointer,world.camera);const hit=model.pick(ray);if(hit)perform('move',hit);},{signal,passive:true});}
 const visibility=()=>{if(owner==='hero')model?.setActive(!document.hidden);if(!ready)return;const active=visible&&!document.hidden;if(active&&owner==='hero'){epoch++;owner='frame';model?.setActive(false);post({type:'bullet-owner',epoch,active:true,snapshot:model?.snapshot()||fallback.snapshot()});}else if(!active&&owner==='frame'){epoch++;owner='transfer';post({type:'bullet-owner',epoch,active:false});}};
 const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting&&entries[0].intersectionRatio>=.15;visibility();},{threshold:[0,.15]});observer.observe(frame);document.addEventListener('visibilitychange',visibility,{signal});
 addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==frame.contentWindow)return;const d=event.data;if(d?.type==='bullet-ready'){ready=true;visibility();}if(d?.type==='bullet-event'&&d.epoch===epoch&&owner==='frame')eventCue(d.event);
  if(d?.type==='bullet-settings'&&d.epoch===epoch&&owner==='frame'&&(model||fallback).restore(d.snapshot)){controls.set(state());if(world)world.moving=1;}
  if(d?.type==='bullet-state'&&d.epoch===epoch&&owner==='transfer'){(model||fallback).restore(d.snapshot);owner='hero';model?.setActive(!document.hidden);controls.set(state());if(world)world.moving=1;visibility();const actions=pending;pending=[];actions.forEach(({action,value})=>perform(action,value));}},{signal});
 signal.addEventListener('abort',()=>{observer.disconnect();post({type:'bullet-owner',epoch:++epoch,active:false});if(model)model.onState=model.onEvent=model.onPick=null;},{once:true});
}
