import * as THREE from 'three';
import {glassControls} from './glass-controls.js';
import {createGlassState} from '../world/glass-state.js';
import {nextBeatDelay} from './domain.js';
export function bindGlass(section,main,{world,score,signal}){
 const model=world?.model,fallback=createGlassState(),frame=main.querySelector('.experiment-frame'),ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let ready=false,visible=false,owner='hero',epoch=0,pending=[];
 const state=()=>model?.state.state||fallback.state,reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches,post=data=>frame.contentWindow?.postMessage(data,location.origin),options=kind=>({wait:kind==='stamp'&&score.audible&&!reduced()?nextBeatDelay(score.time):0,reduced:reduced()});
 const perform=(action,value)=>{if(owner==='transfer'){pending.push({action,value});pending=pending.slice(-8);return;}if(owner==='frame'){post({type:'glass-action',epoch,action,value});if(action==='press')score.cue('hover',value.options?.wait||0);return;}const target=model||fallback;if(action==='press'){target.press(value.kind,model?value.options:{...value.options,reduced:true});score.cue('hover',value.options?.wait||0);}if(action==='move')target.move(value.x,value.y);if(action==='power')target.focus(value);if(action==='freeze')target.freeze(value);if(action==='home'){target.freeze(false);target.move(0,0);target.focus(.65);}controls.set(state());if(world)world.moving=1;};
 const controls=glassControls({signal,onPress:kind=>perform('press',{kind,options:options(kind)}),onPower:value=>perform('power',value),onFreeze:value=>perform('freeze',value),onHome:()=>perform('home')});section.querySelector('.hero-note').remove();section.querySelector('.explore-button').before(controls.element);section.querySelector('.explore-button').textContent='带着这些小变化，走近看看 ↓';main.querySelector('.experiment-intro p').textContent='移动或拖动两块透镜，透过玻璃盖章、换墨、收集发现。下面的纸面是真实可操作的页面；方向键也能移动透镜，空格盖章。';controls.set(state());
 if(model){model.onState=controls.set;model.onComplete=()=>score.cue('reveal');model.onPick=hit=>hit.kind?perform('press',{kind:hit.kind,options:options(hit.kind)}):perform('move',hit);
  addEventListener('pointermove',event=>{if(state().frozen||event.pointerType==='touch'||event.target.closest('a,button,input'))return;const rect=section.getBoundingClientRect();if(event.clientY<rect.top||event.clientY>rect.bottom)return;pointer.set(event.clientX/innerWidth*2-1,1-event.clientY/innerHeight*2);ray.setFromCamera(pointer,world.camera);const hit=ray.intersectObject(model.page)[0];if(hit)perform('move',{x:(hit.uv.x-.5)*3.3/.95,y:(hit.uv.y-.5)*2.3375/.58});},{signal,passive:true});}
 const visibility=()=>{if(owner==='hero')model?.setActive(!document.hidden);if(!ready)return;const active=visible&&!document.hidden;if(active&&owner==='hero'){epoch++;owner='frame';model?.setActive(false);post({type:'glass-owner',epoch,active:true,snapshot:model?.snapshot()||fallback.snapshot()});}else if(!active&&owner==='frame'){epoch++;owner='transfer';post({type:'glass-owner',epoch,active:false});}};
 const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting&&entries[0].intersectionRatio>=.15;visibility();},{threshold:[0,.15]});observer.observe(frame);document.addEventListener('visibilitychange',visibility,{signal});
 addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==frame.contentWindow)return;const data=event.data;if(data?.type==='glass-ready'){ready=true;visibility();}if(data?.type==='glass-settings'&&data.epoch===epoch&&owner==='frame'&&(model||fallback).restore(data.snapshot)){controls.set(state());if(world)world.moving=1;}if(data?.type==='glass-state'&&data.epoch===epoch&&owner==='transfer'){(model||fallback).restore(data.snapshot);owner='hero';model?.setActive(!document.hidden);controls.set(state());if(world)world.moving=1;visibility();const actions=pending;pending=[];actions.forEach(({action,value})=>perform(action,value));}},{signal});
 signal.addEventListener('abort',()=>{observer.disconnect();post({type:'glass-owner',epoch:++epoch,active:false});if(model)model.onState=model.onComplete=model.onPick=null;},{once:true});
}
