import {GLASS_INKS} from '../world/glass-state.js';
import {createLensFilter} from './glass-optics.js';
export function createGlassDesk(host,{signal,onPress}){
 const stage=document.createElement('div');stage.className='glass-stage';stage.tabIndex=0;stage.setAttribute('aria-label','观察台：方向键移动透镜，空格盖章，Home 归位');
 stage.innerHTML='<article class="glass-paper"><div class="glass-paper-meta"><span>FIELD NOTES / ELI3XIR</span><span>NO. 07</span></div><h2>Stay curious.</h2><p class="glass-paper-intro">靠近一点，平常的事也会有新发现。</p><div class="glass-notes"><section class="glass-note"><span class="glass-note-number">01</span><h3>一封小信</h3><p>谢谢你，停下来看看。</p><span class="glass-stamp" aria-hidden="true">收到你的好奇</span><button type="button" data-glass-action="stamp">盖个章</button></section><section class="glass-note"><span class="glass-note-number">02</span><h3>换一笔颜色</h3><p>今天想用哪种颜色？</p><div class="glass-ink-strip" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div><button type="button" data-glass-action="ink">换一笔</button></section><section class="glass-note"><span class="glass-note-number">03</span><h3>好奇心收集处</h3><p>微小的发现也算数。</p><span class="glass-count" aria-hidden="true">00</span><button type="button" data-glass-action="count">发现 +1</button></section></div><footer>A LITTLE CLOSER. A LITTLE DIFFERENT.</footer></article><div class="lens glass-main-lens" aria-hidden="true"></div><div class="lens glass-small-lens" aria-hidden="true"></div>';
 host.append(stage);stage.querySelectorAll('[data-glass-action]').forEach(button=>button.addEventListener('click',()=>onPress(button.dataset.glassAction),{signal}));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width','0');svg.setAttribute('height','0');svg.setAttribute('aria-hidden','true');host.append(svg);const uid='glass-'+Math.random().toString(36).slice(2),filters=[createLensFilter(svg,uid+'-a'),createLensFilter(svg,uid+'-b')],lenses=[...stage.querySelectorAll('.lens')],paper=stage.querySelector('.glass-paper');
 const refracts=Boolean(globalThis.chrome)&&CSS.supports('backdrop-filter','url(#x)');lenses.forEach((lens,i)=>{if(refracts)lens.style.backdropFilter=`url(#${uid}-${i?'b':'a'})`;});let size=0,bounds,previous='',frames=0;
 function resize(){bounds={width:stage.clientWidth,height:stage.clientHeight};size=Math.min(250,bounds.width*.60,bounds.height*.60);for(let i=0;i<2;i++){const d=Math.round(size*(i?.56:1));filters[i].resize(d);lenses[i].style.width=lenses[i].style.height=d+'px';}}
 function draw(s){frames++;const elastic=s.frozen||matchMedia('(prefers-reduced-motion: reduce)').matches?0:Math.max(-.035,Math.min(.035,(Math.abs(s.vx)-Math.abs(s.vy))*.018));const x=(s.x*.5+.5)*(bounds.width-size)+size/2,y=(-s.y*.5+.5)*(bounds.height-size)+size/2,d2=Math.round(size*.56);lenses[0].style.transform=`translate3d(${x-size/2}px,${y-size/2}px,0) scale(${1+elastic},${1/(1+elastic)})`;lenses[1].style.transform=`translate3d(${(1-(s.x*.35+.5))*(bounds.width-d2)}px,${(.2+s.y*.15)*(bounds.height-d2)}px,0)`;filters.forEach(filter=>filter.set(s.power));const key=[s.ink,s.stampCount,s.count].join(':');if(key!==previous){previous=key;paper.style.setProperty('--note-ink',GLASS_INKS[s.ink]);paper.classList.toggle('is-stamped',s.stamped);stage.querySelector('.glass-stamp').textContent='收到好奇 · '+s.stampCount;stage.querySelector('.glass-count').textContent=String(s.count).padStart(2,'0');stage.querySelector('[data-glass-action="stamp"]').textContent=s.stamped?'再盖一次':'盖个章';stage.querySelector('[data-glass-action="count"]').setAttribute('aria-label',`再收集一个发现，当前 ${s.count} 个`);}}
 return{stage,paper,lenses,filters,resize,draw,point(event){const b=stage.getBoundingClientRect();return{x:Math.max(-1,Math.min(1,((event.clientX-b.left-size/2)/(b.width-size)-.5)*2)),y:Math.max(-1,Math.min(1,(.5-(event.clientY-b.top-size/2)/(b.height-size))*2))};},diagnostics:()=>({refracts,frames,maps:filters.map(f=>f.diagnostics())}),dispose(){filters.forEach(f=>f.dispose());svg.remove();stage.remove();}};
}
