import fs from 'node:fs';import assert from 'node:assert/strict';
import {startServer,launchBrowser,ready,settle,observe,output} from './browser-support.mjs';
const server=process.env.BASE_URL?{base:process.env.BASE_URL,close:async()=>{}}:await startServer(),browser=await launchBrowser(),report={base:server.base,cases:[]};
async function open(page){await page.goto(server.base+'/lab/breakout.html');await ready(page);await settle(page);}
async function enter(page){await page.locator('.hero-copy .explore-button').click();const frame=await(await page.locator('.experiment-frame').elementHandle()).contentFrame();await frame.waitForURL(u=>u.searchParams.has('embedded'));await frame.waitForFunction(()=>window.breakoutExperiment?.diagnostics().active);return frame;}
const snap=(target,child=false)=>target.evaluate(child=>(child?window.breakoutExperiment.state:window.studio.world.model.state).snapshot(),child);
try{
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
  const context=await browser.newContext({viewport,hasTouch:viewport.width<700}),page=await context.newPage(),log=observe(page);await open(page);const idle=await snap(page);await page.waitForTimeout(150);assert.deepEqual(await snap(page),idle);await page.locator('[data-breakout-launch]').click();await page.waitForFunction(()=>window.studio.world.model.state.state.hits>0);await page.locator('[data-breakout-pause]').click();const exact=await snap(page);const frame=await enter(page);assert.deepEqual(await snap(frame,true),exact);await page.evaluate(()=>document.querySelector('.experiment-frame').scrollIntoView({block:'center',behavior:'instant'}));await page.screenshot({path:`${output}/breakout-play-${viewport.width}.png`});
  await frame.locator('canvas').focus();await page.keyboard.press('ArrowRight');assert.equal((await snap(frame,true)).target,.22);await page.keyboard.press('Home');await page.keyboard.press('p');await page.waitForTimeout(120);await page.keyboard.press('p');const moved=await snap(frame,true);assert.ok(moved.time>exact.time);await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);assert.deepEqual(await snap(page),moved);const frames=await frame.evaluate(()=>window.breakoutExperiment.diagnostics().frames);await page.waitForTimeout(180);assert.equal(await frame.evaluate(()=>window.breakoutExperiment.diagnostics().frames),frames);
  for(let i=0;i<4;i++){await page.evaluate(()=>document.querySelector('.experiment-frame').scrollIntoView({block:'center',behavior:'instant'}));await page.waitForTimeout(45);await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(45);}await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);assert.deepEqual(await snap(page),moved);await page.screenshot({path:`${output}/breakout-hero-${viewport.width}.png`});
  const contact=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world;return w.actor.root.getObjectByName('mote-right-hand').getWorldPosition(new T.Vector3()).distanceTo(w.model.board.handle.getWorldPosition(new T.Vector3()));});assert.ok(contact<1e-5,String(contact));
  const resources=await page.evaluate(()=>{const w=window.studio.world,m=w.model,original=m.snapshot(),before={...w.renderer.info.memory},geometry=m.board.tiles.geometry,buffer=m.board.tiles.instanceMatrix.array;for(let i=0;i<30;i++){m.reset();m.launch();for(let j=0;j<125;j++)m.state.update(1/120);m.pause(true);m.update(0,{},0,100+i,false);w.composer.render();}const after={...w.renderer.info.memory};m.restore(original);return{before,after,sameGeometry:geometry===m.board.tiles.geometry,sameBuffer:buffer===m.board.tiles.instanceMatrix.array};});assert.deepEqual(resources.after,resources.before);assert.equal(resources.sameGeometry,true);assert.equal(resources.sameBuffer,true);
  await enter(page);await page.evaluate(()=>document.querySelector('.hero-copy [data-breakout-reset]').click());await frame.waitForFunction(()=>window.breakoutExperiment.state.state.hits===0&&window.breakoutExperiment.state.state.status==='ready');await page.evaluate(()=>document.querySelector('.experiment-frame').scrollIntoView({block:'center',behavior:'instant'}));await page.waitForTimeout(180);
  const point=await frame.evaluate(async()=>{const T=await import('three'),w=window.breakoutExperiment,p=w.model.board.stage.localToWorld(new T.Vector3(.65,-.8,.04)).project(w.camera),b=document.querySelector('canvas').getBoundingClientRect();return{x:b.x+(p.x+1)*b.width/2,y:b.y+(1-p.y)*b.height/2};}),frameBox=await page.locator('.experiment-frame').boundingBox();
  if(viewport.width<700){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:frameBox.x+point.x,y:frameBox.y+point.y,id:1}]});await frame.waitForFunction(()=>window.breakoutExperiment.diagnostics().drag!==null);await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:frameBox.x+point.x-25,y:frameBox.y+point.y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.equal(await frame.evaluate(()=>window.breakoutExperiment.diagnostics().drag),null);await cdp.detach();}else await page.mouse.click(frameBox.x+point.x,frameBox.y+point.y);
  await frame.waitForFunction(()=>window.breakoutExperiment.state.state.status==='playing');assert.notEqual((await snap(frame,true)).target,0);
  const layout=await frame.evaluate(()=>{const c=document.querySelector('canvas').getBoundingClientRect(),controls=document.querySelector('.breakout-controls').getBoundingClientRect(),hud=document.querySelector('.demo-hud').getBoundingClientRect();return{canvas:{top:c.top,bottom:c.bottom},controlsTop:controls.top,hudBottom:hud.bottom,overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(layout.canvas.top>=layout.hudBottom&&layout.canvas.bottom<=layout.controlsTop-8,JSON.stringify(layout));assert.equal(layout.overflow,0);
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);await page.evaluate(()=>{const m=window.studio.world.model;window.breakoutDisposed={};for(const [name,o]of [['tiles',m.board.tiles],['slots',m.board.slots],['shards',m.effects.shards],['trail',m.effects.trail]]){for(const [part,resource]of [['instance',o],['geometry',o.geometry],['material',o.material]]){const k=name+part;window.breakoutDisposed[k]=0;resource.addEventListener('dispose',()=>window.breakoutDisposed[k]++);}}window.breakoutDisposed.texture=0;m.board.texture.addEventListener('dispose',()=>window.breakoutDisposed.texture++);});await page.evaluate(()=>window.studio.router.navigate('/lab/'));await settle(page);const disposed=await page.evaluate(()=>({counts:window.breakoutDisposed,floor:window.studio.world.floor.visible}));assert.ok(Object.values(disposed.counts).every(n=>n===1),JSON.stringify(disposed));assert.equal(disposed.floor,true);assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({viewport,exact,moved,contact,resources,layout,disposed});await context.close();console.log(`PASS breakout shared gameplay ${viewport.width}`);
 }
 {
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),log=observe(page);await open(page);
  const pixels=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,m=w.model,r=w.renderer;w.stop();m.setActive(false);const snapshot=m.snapshot(),parent=m.root.parent,scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,30);scene.background=new T.Color(0);scene.add(new T.HemisphereLight(0xffffff,0x444444,3));camera.position.z=9;scene.add(m.root);const target=new T.WebGLRenderTarget(160,160),old=r.getRenderTarget(),buffers=[];r.setRenderTarget(target);for(const removed of [false,true]){if(removed)m.restore({...snapshot,status:'won',bricks:Array(45).fill(false),score:1350,hits:45,paused:true});m.update(0,{},0,0,true);r.render(scene,camera);const data=new Uint8Array(160*160*4);r.readRenderTargetPixels(target,0,0,160,160,data);buffers.push(data);}r.setRenderTarget(old);target.dispose();parent.add(m.root);m.restore(snapshot);m.setActive(true);w.start();let changed=0,total=0;for(let i=0;i<buffers[0].length;i+=4){let d=0;for(let c=0;c<3;c++)d+=Math.abs(buffers[0][i+c]-buffers[1][i+c]);if(d>5)changed++;total+=d;}return{changed,total};});assert.ok(pixels.changed>200&&pixels.total>10000,JSON.stringify(pixels));
  await page.locator('.sound-toggle').click();await page.waitForFunction(()=>window.studio.score.audible);await page.evaluate(()=>{const m=window.studio.world.model,launch=m.launch.bind(m),onEvent=m.onEvent,score=window.studio.score,cue=score.cue.bind(score);window.breakoutCues=[];score.cue=(kind,delay)=>{window.breakoutCues.push({kind,delay,time:performance.now()});return cue(kind,delay);};m.launch=options=>{window.breakoutStart={score:score.time,delay:options.wait||0,time:performance.now()};return launch(options);};m.onEvent=e=>{if(e.kind==='brick')window.breakoutHit={...e,wall:performance.now()};onEvent(e);};});const hit=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,p=w.model.board.stage.localToWorld(new T.Vector3(0,-1,.05)).project(w.camera);return{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2};});await page.mouse.click(hit.x,hit.y);await page.waitForFunction(()=>window.breakoutStart);await page.evaluate(()=>window.studio.score.context.suspend());await page.waitForFunction(()=>window.breakoutHit);const timing=await page.evaluate(()=>({start:window.breakoutStart,hit:window.breakoutHit,cues:window.breakoutCues}));assert.ok(Math.abs((timing.start.score+timing.start.delay)*112/60*2-Math.round((timing.start.score+timing.start.delay)*112/60*2))<.04);assert.ok(timing.hit.wall>timing.start.time);assert.ok(timing.cues.some(c=>/^brick/.test(c.kind)));assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'GPU brick removal, physical launch and audio interruption',pixels,timing});await page.close();console.log('PASS breakout pixels and timing');
 }
 {
  const page=await browser.newPage(),log=observe(page),layouts=[];
  for(const viewport of [{width:320,height:568},{width:390,height:844},{width:768,height:1024},{width:844,height:390}]){await page.setViewportSize(viewport);await open(page);const bounds=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,m=w.model,p=new T.Vector3(),im=new T.Matrix4(),combined=new T.Matrix4(),bottom=document.querySelector('.hero-copy').getBoundingClientRect().bottom;w.stop();m.setActive(false);let left=Infinity,right=-Infinity,top=Infinity;for(const x of [-1.42,0,1.42])for(const y of [-2.13,0,1.936]){const s=m.snapshot();m.restore({...s,paddle:x,target:x,x,y});w.frame(performance.now());for(const root of [m.root,w.actor.root])root.traverseVisible(o=>{if(!o.isMesh)return;o.updateWorldMatrix(true,false);for(let instance=0;instance<(o.isInstancedMesh?o.count:1);instance++){if(o.isInstancedMesh){o.getMatrixAt(instance,im);combined.multiplyMatrices(o.matrixWorld,im);}else combined.copy(o.matrixWorld);const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){p.fromBufferAttribute(a,i).applyMatrix4(combined).project(w.camera);left=Math.min(left,(p.x+1)*innerWidth/2);right=Math.max(right,(p.x+1)*innerWidth/2);top=Math.min(top,(1-p.y)*innerHeight/2);}}});}return{left,right,gap:top-bottom,overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(bounds.left>=-.1&&bounds.right<=viewport.width+.1&&bounds.gap>8,JSON.stringify({viewport,bounds}));assert.equal(bounds.overflow,0);layouts.push({viewport,...bounds});}assert.deepEqual(log.errors,[]);report.cases.push({name:'compact board and full paddle travel',layouts});await page.close();console.log('PASS breakout compact');
 }
 {
  const context=await browser.newContext({reducedMotion:'reduce'}),page=await context.newPage(),log=observe(page);await open(page);const first=await snap(page);await page.waitForTimeout(160);assert.deepEqual(await snap(page),first);await page.locator('.hero-copy .explore-button').click();const frame=await(await page.locator('.experiment-frame').elementHandle()).contentFrame();await frame.waitForURL(u=>u.searchParams.has('embedded'));await frame.locator('.experiment-gate button').waitFor();assert.equal(await frame.evaluate(()=>Boolean(window.breakoutExperiment)),false);await frame.locator('.experiment-gate button').click();await frame.waitForFunction(()=>window.breakoutExperiment?.diagnostics().active);await frame.locator('canvas').focus();await page.keyboard.press('Space');await frame.waitForFunction(()=>window.breakoutExperiment.state.state.hits>0);await page.keyboard.press('p');const exact=await snap(frame,true);await page.waitForTimeout(150);assert.deepEqual(await snap(frame,true),exact);assert.equal(await frame.evaluate(()=>window.breakoutExperiment.model.effects.shards.count+window.breakoutExperiment.model.effects.trail.count),0);assert.deepEqual(log.errors,[]);report.cases.push({name:'reduced explicit essential gameplay without secondary effects'});await context.close();console.log('PASS breakout reduced');
 }
 {
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),log=observe(page);await page.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:original.call(this,type,...args);};});await open(page);const frame=await enter(page);await frame.locator('canvas').focus();await page.keyboard.press('Space');await frame.waitForFunction(()=>window.breakoutExperiment.state.state.hits>0);await page.keyboard.press('p');const exact=await snap(frame,true);assert.equal(await frame.evaluate(()=>window.breakoutExperiment.renderer),null);await page.screenshot({path:`${output}/breakout-flat.png`});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await frame.waitForFunction(()=>!window.breakoutExperiment.diagnostics().active);await enter(page);assert.deepEqual(await snap(frame,true),exact);await frame.locator('canvas').focus();await page.keyboard.press('r');await frame.waitForFunction(()=>window.breakoutExperiment.state.state.status==='ready');assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'no WebGL preserves keyboard gameplay and exact paused state',exact});await context.close();console.log('PASS breakout flat');
 }
 {
  const page=await browser.newPage(),log=observe(page),layouts=[];for(const viewport of [{width:1440,height:1000},{width:1280,height:900},{width:1366,height:768},{width:1280,height:720}]){await page.setViewportSize(viewport);await open(page);const layout=await page.evaluate(()=>{const copy=document.querySelector('.hero-copy').getBoundingClientRect(),dock=document.querySelector('.sound-dock').getBoundingClientRect(),header=document.querySelector('.studio-header').getBoundingClientRect(),words=[...document.querySelectorAll('.hero-word')].map(e=>e.getBoundingClientRect().right);return{top:copy.top,header:header.bottom,gap:dock.top-copy.bottom,titleRight:Math.max(...words),copyRight:copy.right};});await page.screenshot({path:`${output}/breakout-desktop-${viewport.width}-${viewport.height}.png`});assert.ok(layout.gap>=12&&layout.top>layout.header&&layout.titleRight<=layout.copyRight+1,JSON.stringify({viewport,layout}));layouts.push({viewport,...layout});}assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'desktop type and controls clear fixed sound dock',layouts});await page.close();console.log('PASS breakout desktop');
 }
}finally{fs.writeFileSync(`${output}/breakout-audit.json`,JSON.stringify(report,null,2));await browser.close();await server.close();}console.log(JSON.stringify({base:report.base,cases:report.cases.length}));
