import fs from 'node:fs';
import assert from 'node:assert/strict';
import {startServer,launchBrowser,ready,settle,observe,output} from './browser-support.mjs';
const server=process.env.BASE_URL?{base:process.env.BASE_URL,close:async()=>{}}:await startServer(),browser=await launchBrowser(),report={base:server.base,cases:[]};
async function frameOf(page){const frame=await(await page.locator('.experiment-frame').elementHandle()).contentFrame();await frame.waitForURL(url=>url.searchParams.has('embedded'),{waitUntil:'domcontentloaded'});return frame;}
async function state(target,embedded=false){return target.evaluate(embedded=>{
 const m=embedded?window.fluidExperiment.model:window.studio.world.model,start=performance.now(),f=m.snapshot().field;
 const fields={};for(const name of ['velocity','pressure','dye']){const a=f[name],words=new Uint32Array(a.buffer);let hash=2166136261,sum=0,max=0,invalid=0;for(let i=0;i<a.length;i++){hash=Math.imul(hash^words[i],16777619);sum+=a[i];max=Math.max(max,Math.abs(a[i]));if(!Number.isFinite(a[i]))invalid++;}fields[name]={hash:hash>>>0,sum,max,invalid};}
 return{...m.diagnostics(),fields,readAndHashMs:performance.now()-start};
},embedded);}
function sameFields(a,b){assert.deepEqual(a.fields,b.fields);assert.equal(a.steps,b.steps);assert.equal(a.nozzleX,b.nozzleX);}
async function remember(target,embedded=false){await target.evaluate(embedded=>{parent.fluidExpected=(embedded?window.fluidExperiment.model:window.studio.world.model).snapshot().field;},embedded);}
async function exact(target,embedded=false){assert.equal(await target.evaluate(embedded=>{const field=(embedded?window.fluidExperiment.model:window.studio.world.model).snapshot().field,expected=parent.fluidExpected;return ['velocity','pressure','dye'].every(key=>field[key].length===expected[key].length&&field[key].every((value,i)=>Object.is(value,expected[key][i])));},embedded),true);}
async function open(page){await page.goto(server.base+'/lab/fluid.html');await ready(page);await settle(page);}
try{
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
  const context=await browser.newContext({viewport,hasTouch:viewport.width<700}),page=await context.newPage(),log=observe(page);await open(page);await page.locator('[data-fluid-pause]').click();await page.locator('[data-pigment="4"]').click();
  const paused=await state(page);assert.equal(paused.kind,'gpu');assert.ok(paused.fields.dye.sum>0);await page.waitForTimeout(180);sameFields(paused,await state(page));await remember(page);await page.screenshot({path:`${output}/fluid-hero-${viewport.width}.png`});
  await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.waitForFunction(()=>window.fluidExperiment?.diagnostics().active&&window.fluidExperiment.diagnostics().color===4);const after=await state(frame,true);sameFields(paused,after);await exact(frame,true);assert.equal(after.paused,true);assert.equal(await page.evaluate(()=>window.studio.world.model.diagnostics().active),false);
  const origin=await frame.evaluate(()=>window.fluidExperiment.diagnostics().point);await frame.locator('canvas').focus();await page.keyboard.press('ArrowLeft');await page.keyboard.press('ArrowDown');const point=await frame.evaluate(()=>window.fluidExperiment.diagnostics().point);assert.ok(point[0]<origin[0]&&point[1]<origin[1]);await page.keyboard.press('Space');await frame.waitForFunction(()=>window.fluidExperiment.diagnostics().drop===null);const dropped=await state(frame,true);assert.ok(dropped.fields.dye.sum>after.fields.dye.sum);assert.equal(dropped.steps,after.steps);
  await frame.locator('[data-fluid-clear]').click();const clear=await state(frame,true);assert.equal(clear.fields.dye.sum,0);assert.equal(clear.fields.velocity.sum,0);assert.equal(clear.fields.pressure.sum,0);
  const box=await frame.locator('canvas').boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await frame.waitForFunction(()=>window.fluidExperiment.diagnostics().drag!==null);await page.mouse.move(box.x+box.width*.64,box.y+box.height*.6,{steps:12});await page.mouse.up();assert.equal(await frame.evaluate(()=>window.fluidExperiment.diagnostics().drag),null);assert.equal(await frame.evaluate(()=>window.fluidExperiment.diagnostics().color),0);const brush=await state(frame,true);assert.ok(brush.fields.dye.sum>0);
  if(viewport.width<700){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width*.5,y:box.y+box.height*.5,id:4}]});await frame.waitForFunction(()=>window.fluidExperiment.diagnostics().drag!==null);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await frame.waitForFunction(()=>window.fluidExperiment.diagnostics().drag===null);await cdp.detach();}
  const expected=await state(frame,true);await remember(frame,true);await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);const returned=await state(page);sameFields(expected,returned);await exact(page);await frame.waitForFunction(()=>!window.fluidExperiment.diagnostics().active);const frames=await frame.evaluate(()=>window.fluidExperiment.diagnostics().frames);await page.waitForTimeout(200);assert.equal(await frame.evaluate(()=>window.fluidExperiment.diagnostics().frames),frames);
  for(let i=0;i<4;i++){await page.evaluate(()=>document.querySelector('.experiment-frame').scrollIntoView({behavior:'instant',block:'center'}));await page.waitForTimeout(45);await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(45);}
  await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);sameFields(expected,await state(page));await exact(page);
  await page.locator('.hero-copy .explore-button').click();await frame.waitForFunction(()=>window.fluidExperiment.diagnostics().active);await frame.locator('[data-fluid-pause]').click();await frame.waitForFunction(s=>window.fluidExperiment.diagnostics().steps>s,expected.steps);await page.waitForTimeout(800);await page.screenshot({path:`${output}/fluid-play-${viewport.width}.png`});
  const resource=await frame.evaluate(()=>({...window.fluidExperiment.renderer.info.memory}));await frame.evaluate(()=>{const m=window.fluidExperiment.model;m.setPaused(true);for(let i=0;i<24;i++){const snapshot=m.snapshot();m.inject([.3+i*.01,.4],[.3,-.1]);m.restore(snapshot);}});const resourceAfter=await frame.evaluate(()=>({...window.fluidExperiment.renderer.info.memory}));assert.deepEqual(resourceAfter,resource);
  const layout=await frame.evaluate(()=>{const c=document.querySelector('canvas').getBoundingClientRect(),h=document.querySelector('.demo-hud').getBoundingClientRect(),f=document.querySelector('.fluid-controls').getBoundingClientRect();return{canvasTop:c.top,canvasBottom:c.bottom,hudBottom:h.bottom,controlsTop:f.top,overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(layout.canvasTop>=layout.hudBottom,JSON.stringify(layout));assert.ok(layout.canvasBottom<=layout.controlsTop,JSON.stringify(layout));assert.equal(layout.overflow,0);
  const envelope=await frame.evaluate(async()=>{const T=await import('three'),e=window.fluidExperiment,p=new T.Vector3();let x=0,y=0;e.model.root.updateMatrixWorld(true);e.model.root.traverseVisible(o=>{if(!o.isMesh)return;const positions=o.geometry.attributes.position;for(let i=0;i<positions.count;i++){p.fromBufferAttribute(positions,i).applyMatrix4(o.matrixWorld).project(e.camera);x=Math.max(x,Math.abs(p.x));y=Math.max(y,Math.abs(p.y));}});return{x,y};});assert.ok(envelope.x<1&&envelope.y<1,JSON.stringify(envelope));layout.envelope=envelope;
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);const cleanup=await page.evaluate(async()=>{const T=await import('three'),m=window.studio.world.model;window.fluidOld=m;window.fluidReleased={target:0,geometry:0,material:0};const original=T.WebGLRenderTarget.prototype.dispose;T.WebGLRenderTarget.prototype.dispose=function(){window.fluidReleased.target++;return original.call(this);};window.fluidRestoreDispose=()=>{T.WebGLRenderTarget.prototype.dispose=original;};m.cell.surface.geometry.addEventListener('dispose',()=>window.fluidReleased.geometry++);m.cell.surface.material.addEventListener('dispose',()=>window.fluidReleased.material++);return m.diagnostics();});await page.evaluate(()=>window.studio.router.navigate('/lab/'));await settle(page);const disposed=await page.evaluate(()=>{window.fluidRestoreDispose();return{counts:window.fluidReleased,pick:window.fluidOld.onPick};});assert.equal(disposed.counts.target,9);assert.equal(disposed.counts.geometry,1);assert.equal(disposed.counts.material,1);assert.equal(disposed.pick,null);assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);
  report.cases.push({viewport,paused,after,dropped,brush,returned,layout,resource,cleanup,disposed});await context.close();console.log(`PASS fluid exact state, input, ownership, resources ${viewport.width}`);
 }
 {
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),log=observe(page);await open(page);
  const numerical=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,m=w.model,sim=m.simulation;w.stop();const original=m.snapshot();
   function divergence(field){let sum=0,count=0;for(let y=2;y<78;y++)for(let x=2;x<126;x++){const k=(y*128+x)*4,d=(field[k+4]-field[k-4]+field[k+513]-field[k-511])*40;sum+=d*d;count++;}return Math.sqrt(sum/count);}
   sim.clear();sim.inject(.5,.5,1,-.6,2,1,.1);const before=divergence(sim.snapshot().velocity);for(let i=0;i<12;i++)sim.step(1/60);const snapshot=sim.snapshot(),after=divergence(snapshot.velocity);let finite=true;for(const key of ['dye','velocity','pressure'])finite&&=snapshot[key].every(Number.isFinite);
   const target=new T.WebGLRenderTarget(32,24);w.renderer.setRenderTarget(target);const auto=w.renderer.autoClear,xr=w.renderer.xr.enabled;sim.step(1/60);const preserved=w.renderer.getRenderTarget()===target&&w.renderer.autoClear===auto&&w.renderer.xr.enabled===xr;w.renderer.setRenderTarget(null);target.dispose();
   const bad={...snapshot,dye:snapshot.dye.slice()};bad.dye[17]=NaN;const invalidRejected=!sim.restore(bad);m.setPaused(true);m.setActive(true);m.update(0,{},0,10);m.addDrop({uv:[.75,.5]});m.update(0,{},0,10.3);m.update(0,{},0,10.54);const completedWithLargeFrames=m.diagnostics().drop===null;m.restore(original);w.start();return{before,after,finite,preserved,invalidRejected,completedWithLargeFrames};});assert.ok(numerical.after<numerical.before*.6,JSON.stringify(numerical));assert.equal(numerical.finite,true);assert.equal(numerical.preserved,true);assert.equal(numerical.invalidRejected,true);assert.equal(numerical.completedWithLargeFrames,true);
  await page.locator('.sound-toggle').click();await page.waitForFunction(()=>window.studio.score.audible);await page.evaluate(()=>{const m=window.studio.world.model,add=m.addDrop.bind(m),end=m.onDrop;m.addDrop=options=>{window.fluidStart={time:window.studio.score.time,delay:options.delay||0,start:performance.now()};return add(options);};m.onDrop=()=>{window.fluidEnd=performance.now();end();};});
  await page.mouse.click(1410,120);assert.equal(await page.evaluate(()=>window.studio.world.model.diagnostics().drop),null);const hit=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,p=w.model.cell.surface.localToWorld(new T.Vector3(.3,.2,0)).project(w.camera);return{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2};});await page.mouse.click(hit.x,hit.y);await page.waitForFunction(()=>window.fluidStart);await page.evaluate(()=>window.studio.score.context.suspend());await page.waitForFunction(()=>window.fluidEnd);const timing=await page.evaluate(()=>({...window.fluidStart,duration:(window.fluidEnd-window.fluidStart.start)/1000-window.fluidStart.delay}));assert.ok(Math.abs((timing.time+timing.delay)*112/60*2-Math.round((timing.time+timing.delay)*112/60*2))<.04);assert.ok(Math.abs(timing.duration-60/112)<.13,JSON.stringify(timing));
  await page.locator('[data-fluid-pause]').click();await page.locator('[data-fluid-drop]').click();await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.waitForFunction(()=>window.fluidExperiment?.diagnostics().active);await frame.waitForFunction(()=>window.fluidExperiment.diagnostics().drop===null);const complete=await state(frame,true);assert.equal(complete.paused,true);assert.ok(complete.fields.dye.sum>0);assert.deepEqual(log.errors,[]);report.cases.push({name:'divergence, renderer state, timing and drop handoff',numerical,timing,complete});await page.close();console.log('PASS fluid numerical and timing');
 }
 {
  const context=await browser.newContext(),page=await context.newPage(),log=observe(page),layouts=[];
  for(const viewport of [{width:320,height:568},{width:390,height:844},{width:768,height:1024},{width:844,height:390}]){await page.setViewportSize(viewport);await open(page);const layout=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,m=w.model;w.stop();m.setPaused(true);const now=performance.now(),bottom=document.querySelector('.hero-copy').getBoundingClientRect().bottom;let left=Infinity,right=-Infinity,top=Infinity;for(let i=0;i<40;i++){m.addDrop({uv:[i%2?.05:.95,.8]});w.frame(now+i*20);const box=new T.Box3().setFromObject(m.root).union(new T.Box3().setFromObject(w.actor.root));for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const p=new T.Vector3(x,y,z).project(w.camera);left=Math.min(left,(p.x+1)*innerWidth/2);right=Math.max(right,(p.x+1)*innerWidth/2);top=Math.min(top,(1-p.y)*innerHeight/2);}}return{left,right,gap:top-bottom,scale:w.layoutScale,overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(layout.left>=-.1&&layout.right<=viewport.width+.1,JSON.stringify(layout));assert.ok(layout.gap>8,JSON.stringify(layout));assert.equal(layout.overflow,0);layouts.push({viewport,...layout});await page.screenshot({path:`${output}/fluid-layout-${viewport.width}.png`});}
  assert.deepEqual(log.errors,[]);report.cases.push({name:'compact drop envelope',layouts});await context.close();console.log('PASS fluid compact');
 }
 {
  const context=await browser.newContext({reducedMotion:'reduce'}),page=await context.newPage(),log=observe(page);await open(page);const before=await state(page);await page.waitForTimeout(200);sameFields(before,await state(page));await page.locator('[data-fluid-drop]').click();assert.equal(await page.evaluate(()=>window.studio.world.model.diagnostics().drop),null);assert.ok((await state(page)).fields.dye.sum>before.fields.dye.sum);await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.locator('.experiment-gate button').waitFor();assert.equal(await frame.evaluate(()=>Boolean(window.fluidExperiment)),false);await frame.locator('.experiment-gate button').click();await frame.waitForFunction(()=>window.fluidExperiment?.diagnostics().steps>0);const pose=()=>frame.evaluate(()=>{const values=[];window.fluidExperiment.actor.root.traverse(o=>values.push([...o.position.toArray(),...o.quaternion.toArray(),...o.scale.toArray()]));return values;});const still=await pose();await page.waitForTimeout(200);assert.deepEqual(await pose(),still);assert.deepEqual(log.errors,[]);report.cases.push({name:'reduced static hero, explicit flow, still actor'});await context.close();console.log('PASS fluid reduced');
 }
 for(const kind of ['no-float','no-webgl']){
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),log=observe(page);await page.addInitScript(kind=>{if(kind==='no-webgl'){const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:get.call(this,type,...args);};}else{for(const proto of [WebGLRenderingContext.prototype,WebGL2RenderingContext.prototype]){const get=proto.getExtension,all=proto.getSupportedExtensions;proto.getExtension=function(name){return name==='EXT_color_buffer_float'?null:get.call(this,name);};proto.getSupportedExtensions=function(){return all.call(this).filter(name=>name!=='EXT_color_buffer_float');};}}},kind);await open(page);
  if(kind==='no-webgl')assert.equal(await page.locator('[data-fluid-drop]').isVisible(),false);else assert.equal(await page.evaluate(()=>window.studio.world.model.diagnostics().kind),'cpu');await page.locator('[data-pigment="3"]').click();await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.waitForFunction(()=>window.fluidExperiment?.diagnostics().active&&window.fluidExperiment.diagnostics().color===3);await frame.locator('[data-fluid-pause]').click();const initial=await state(frame,true);assert.equal(initial.kind,'cpu');await frame.locator('[data-fluid-clear]').click();assert.equal((await state(frame,true)).fields.dye.sum,0);await frame.locator('canvas').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Space');await frame.waitForFunction(()=>window.fluidExperiment.diagnostics().drop===null);assert.ok((await state(frame,true)).fields.dye.sum>0);await page.screenshot({path:`${output}/fluid-${kind}.png`});const perf=await frame.evaluate(()=>{const s=window.fluidExperiment.model.simulation,start=performance.now();for(let i=0;i<20;i++)s.step(1/60);return{averageCpuStepMs:(performance.now()-start)/20,gl:Boolean(window.fluidExperiment.renderer)};});assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:kind,initial,perf});await context.close();console.log(`PASS fluid ${kind}`);
 }
}finally{fs.writeFileSync(`${output}/fluid-audit.json`,JSON.stringify(report,null,2));await browser.close();await server.close();}console.log(JSON.stringify({base:report.base,cases:report.cases.length}));
