import fs from 'node:fs';
import assert from 'node:assert/strict';
import {startServer,launchBrowser,ready,settle,observe,output} from './browser-support.mjs';
const server=process.env.BASE_URL?{base:process.env.BASE_URL,close:async()=>{}}:await startServer(),browser=await launchBrowser(),report={base:server.base,cases:[]};
async function open(page){await page.goto(server.base+'/lab/galaxy.html');await ready(page);await settle(page);}
async function frameOf(page){const frame=await(await page.locator('.experiment-frame').elementHandle()).contentFrame();await frame.waitForURL(url=>url.searchParams.has('embedded'),{waitUntil:'domcontentloaded'});return frame;}
const state=(target,embedded=false)=>target.evaluate(embedded=>embedded?window.galaxyExperiment.diagnostics():window.studio.world.model.diagnostics(),embedded);
const snapshot=(target,embedded=false)=>target.evaluate(embedded=>(embedded?window.galaxyExperiment.state:window.studio.world.model.state).snapshot(),embedded);
async function aligned(frame){await frame.waitForFunction(()=>{const s=window.galaxyExperiment.diagnostics();return !s.changing&&s.yaw===s.targetYaw&&s.tilt===s.targetTilt&&s.zoom===s.targetZoom;});}
const pose=frame=>frame.evaluate(()=>{const a=[];window.galaxyExperiment.actor.root.traverse(o=>a.push([...o.position.toArray(),...o.quaternion.toArray(),...o.scale.toArray()]));return a;});
try{
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
  const context=await browser.newContext({viewport,hasTouch:viewport.width<700}),page=await context.newPage(),log=observe(page);await open(page);await page.locator('[data-galaxy-pause]').click();await page.locator('[data-galaxy-band="1"]').click();await page.waitForTimeout(650);const before=await state(page);await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.waitForFunction(()=>window.galaxyExperiment?.diagnostics().active);const after=await state(frame,true);assert.ok(after.band>=before.band);assert.equal(after.angle,before.angle);assert.equal(after.paused,true);await aligned(frame);await page.evaluate(()=>document.querySelector('.experiment-frame').scrollIntoView({block:'center',behavior:'instant'}));await page.screenshot({path:`${output}/galaxy-dust-${viewport.width}.png`});
  const contact=await frame.evaluate(async()=>{const T=await import('three'),e=window.galaxyExperiment;e.model.root.updateMatrixWorld(true);const hand=e.actor.root.getObjectByName('mote-right-hand').getWorldPosition(new T.Vector3()),handle=e.model.selector.handle.getWorldPosition(new T.Vector3());return hand.distanceTo(handle);});assert.ok(contact<.00001,String(contact));
  const box=await frame.locator('canvas').boundingBox(),center={x:box.x+box.width*.5,y:box.y+box.height*.45};await page.mouse.move(center.x,center.y);await page.mouse.down();await page.mouse.move(center.x+35,center.y-22,{steps:10});await page.mouse.up();assert.equal((await state(frame,true)).pointers,0);assert.ok((await state(frame,true)).targetYaw>0);const zoom=(await state(frame,true)).targetZoom;await page.mouse.wheel(0,-100);await frame.waitForFunction(z=>window.galaxyExperiment.diagnostics().targetZoom>z,zoom);
  if(viewport.width<700){const cdp=await context.newCDPSession(page),points=[{x:center.x-30,y:center.y,id:1},{x:center.x+30,y:center.y,id:2}];await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points});await frame.waitForFunction(()=>window.galaxyExperiment.diagnostics().pointers===2);const start=(await state(frame,true)).targetZoom;await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points.map((p,i)=>({...p,x:p.x+(i?12:-12)}))});assert.ok((await state(frame,true)).targetZoom>start);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await frame.waitForFunction(()=>window.galaxyExperiment.diagnostics().pointers===0);await cdp.detach();}
  await frame.locator('canvas').focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowLeft');await page.keyboard.press('ArrowDown');await page.keyboard.press('b');await aligned(frame);assert.equal((await state(frame,true)).targetBand,0);await page.screenshot({path:`${output}/galaxy-visible-${viewport.width}.png`});const exact=await snapshot(frame,true);await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);assert.deepEqual(await snapshot(page),exact);await frame.waitForFunction(()=>!window.galaxyExperiment.diagnostics().active);const stopped=(await state(frame,true)).frames;await page.waitForTimeout(180);assert.equal((await state(frame,true)).frames,stopped);
  for(let i=0;i<4;i++){await page.evaluate(()=>document.querySelector('.experiment-frame').scrollIntoView({block:'center',behavior:'instant'}));await page.waitForTimeout(45);await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(45);}await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);assert.deepEqual(await snapshot(page),exact);await page.screenshot({path:`${output}/galaxy-hero-${viewport.width}.png`});
  await page.locator('.hero-copy .explore-button').click();await frame.waitForFunction(()=>window.galaxyExperiment.diagnostics().active);await page.evaluate(()=>document.querySelector('.hero-copy [data-galaxy-band="1"]').click());await frame.waitForFunction(()=>window.galaxyExperiment.diagnostics().band===1);await frame.locator('canvas').focus();await page.keyboard.press('Space');await frame.waitForFunction(()=>window.galaxyExperiment.diagnostics().angle!==parent.studio.world.model.diagnostics().angle||window.galaxyExperiment.diagnostics().spin>0);assert.equal((await state(frame,true)).paused,false);await frame.locator('[data-galaxy-pause]').click();
  const resources=await frame.evaluate(()=>{const e=window.galaxyExperiment,m=e.model,field=m.field,position=field.stars.geometry.attributes.position,array=position.array,texture=field.uniforms.densityMap.value,original=m.snapshot(),before={...e.renderer.info.memory};for(let i=0;i<24;i++){m.selectBand(i%2,{reduced:true});m.update(0,{},0,100+i,true);e.renderer.render(m.root.parent,e.camera);}m.restore(original);return{before,after:{...e.renderer.info.memory},sameArray:position.array===array,sameTexture:field.uniforms.densityMap.value===texture,version:position.version,count:position.count};});assert.deepEqual(resources.before,resources.after);assert.equal(resources.sameArray,true);assert.equal(resources.sameTexture,true);assert.equal(resources.version,0);assert.equal(resources.count,60000);
  const layout=await frame.evaluate(()=>{const c=document.querySelector('canvas').getBoundingClientRect(),h=document.querySelector('.demo-hud').getBoundingClientRect(),f=document.querySelector('.galaxy-controls').getBoundingClientRect();return{canvasTop:c.top,canvasBottom:c.bottom,hudBottom:h.bottom,controlsTop:f.top,overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(layout.canvasTop>=layout.hudBottom&&layout.canvasBottom<=layout.controlsTop,JSON.stringify(layout));assert.equal(layout.overflow,0);
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);await page.evaluate(()=>{const m=window.studio.world.model;window.galaxyOld=m;window.galaxyDisposed={};for(const [name,item] of [['stars',m.field.stars],['haze',m.field.haze]])for(const type of ['geometry','material']){const key=name+type;window.galaxyDisposed[key]=0;item[type].addEventListener('dispose',()=>window.galaxyDisposed[key]++);}window.galaxyDisposed.texture=0;m.field.uniforms.densityMap.value.addEventListener('dispose',()=>window.galaxyDisposed.texture++);});await page.evaluate(()=>window.studio.router.navigate('/lab/'));await settle(page);const disposed=await page.evaluate(()=>({counts:window.galaxyDisposed,pick:window.galaxyOld.onPick,background:window.studio.world.scene.background.toArray(),floor:window.studio.world.floor.visible}));assert.ok(Object.values(disposed.counts).every(n=>n===1));assert.equal(disposed.pick,null);assert.deepEqual(disposed.background,[16/255,21/255,19/255]);assert.equal(disposed.floor,true);assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({viewport,before,after,contact,resources,layout,disposed});await context.close();console.log(`PASS galaxy state, contact, input and resources ${viewport.width}`);
 }
 {
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),log=observe(page);await open(page);
  const pixels=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,field=w.model.field,r=w.renderer;w.stop();const previous=field.root.parent,scene=new T.Scene(),camera=new T.PerspectiveCamera(42,1,.1,20);scene.background=new T.Color(0);camera.position.set(0,3.4,5.6);camera.lookAt(0,0,0);scene.add(field.root);const target=new T.WebGLRenderTarget(160,160),originalTarget=r.getRenderTarget(),originalBand=field.uniforms.band.value,buffers=[];r.setRenderTarget(target);for(const band of [0,1]){field.setBand(band);r.render(scene,camera);const data=new Uint8Array(160*160*4);r.readRenderTargetPixels(target,0,0,160,160,data);buffers.push(data);}r.setRenderTarget(originalTarget);target.dispose();previous.add(field.root);field.setBand(originalBand);w.start();let changed=0,difference=0;const sums=[[0,0,0],[0,0,0]];for(let i=0;i<160*160;i++){let diff=0;for(let c=0;c<3;c++){diff+=Math.abs(buffers[0][i*4+c]-buffers[1][i*4+c]);sums[0][c]+=buffers[0][i*4+c];sums[1][c]+=buffers[1][i*4+c];}difference+=diff;if(diff>5)changed++;}return{changed,difference,sums};});assert.ok(pixels.changed>1000&&pixels.difference>30000,JSON.stringify(pixels));
  await page.locator('.sound-toggle').click();await page.waitForFunction(()=>window.studio.score.audible);await page.evaluate(()=>{const m=window.studio.world.model,select=m.selectBand.bind(m),done=m.onComplete;m.selectBand=(value,options)=>{window.galaxyStart={time:window.studio.score.time,delay:options.wait||0,start:performance.now()};return select(value,options);};m.onComplete=()=>{window.galaxyEnd=performance.now();done();};});const hit=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,p=w.model.selector.handle.getWorldPosition(new T.Vector3()).project(w.camera);return{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2};});await page.mouse.click(hit.x,hit.y);await page.waitForFunction(()=>window.galaxyStart);await page.evaluate(()=>window.studio.score.context.suspend());await page.waitForFunction(()=>window.galaxyEnd);const timing=await page.evaluate(()=>({...window.galaxyStart,duration:(window.galaxyEnd-window.galaxyStart.start)/1000-window.galaxyStart.delay}));assert.ok(Math.abs((timing.time+timing.delay)*112/60*2-Math.round((timing.time+timing.delay)*112/60*2))<.04);assert.ok(Math.abs(timing.duration-4*60/112)<.13,JSON.stringify(timing));assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'real GPU band change, physical filter and audio interruption',pixels,timing});await page.close();console.log('PASS galaxy pixels and timing');
 }
 {
  const page=await browser.newPage(),log=observe(page),layouts=[];
  for(const viewport of [{width:320,height:568},{width:390,height:844},{width:768,height:1024},{width:844,height:390}]){await page.setViewportSize(viewport);await open(page);const layout=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,m=w.model,p=new T.Vector3();w.stop();m.setActive(false);const now=performance.now(),bottom=document.querySelector('.hero-copy').getBoundingClientRect().bottom;let left=Infinity,right=-Infinity,top=Infinity;for(let i=0;i<16;i++){const s=m.snapshot();m.restore({...s,angle:i*.39,tilt:i%2?1.45:.06,targetTilt:i%2?1.45:.06,zoom:i%3?1.5:.65,targetZoom:i%3?1.5:.65});w.frame(now+i*16);m.root.updateMatrixWorld(true);const measure=(point,matrix)=>{point.applyMatrix4(matrix).project(w.camera);left=Math.min(left,(point.x+1)*innerWidth/2);right=Math.max(right,(point.x+1)*innerWidth/2);top=Math.min(top,(1-point.y)*innerHeight/2);};const stars=m.field.stars.geometry.attributes.position;for(let j=0;j<stars.count;j++)measure(p.fromBufferAttribute(stars,j),m.field.stars.matrixWorld);for(const root of [m.selector.root,w.actor.root])root.traverseVisible(o=>{if(!o.isMesh)return;const a=o.geometry.attributes.position;for(let j=0;j<a.count;j++)measure(p.fromBufferAttribute(a,j),o.matrixWorld);});}return{left,right,gap:top-bottom,scale:w.layoutScale,overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(layout.left>=-.1&&layout.right<=viewport.width+.1&&layout.gap>8,JSON.stringify(layout));assert.equal(layout.overflow,0);layouts.push({viewport,...layout});await page.screenshot({path:`${output}/galaxy-layout-${viewport.width}.png`});}assert.deepEqual(log.errors,[]);report.cases.push({name:'four compact orientations and zoom envelopes',layouts});await page.close();console.log('PASS galaxy compact');
 }
 {
  const context=await browser.newContext({reducedMotion:'reduce'}),page=await context.newPage(),log=observe(page);await open(page);const first=await snapshot(page);await page.waitForTimeout(200);assert.deepEqual(await snapshot(page),first);await page.locator('[data-galaxy-band="1"]').click();assert.equal((await state(page)).band,1);await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.locator('.experiment-gate button').waitFor();assert.equal(await frame.evaluate(()=>Boolean(window.galaxyExperiment)),false);await frame.locator('.experiment-gate button').click();await frame.waitForFunction(()=>window.galaxyExperiment?.diagnostics().active);await frame.locator('[data-galaxy-band="0"]').click();await frame.waitForFunction(()=>window.galaxyExperiment.diagnostics().band===0);await page.waitForTimeout(80);const still=await pose(frame),angle=(await state(frame,true)).angle;await page.waitForTimeout(220);assert.deepEqual(await pose(frame),still);assert.equal((await state(frame,true)).angle,angle);await page.screenshot({path:`${output}/galaxy-reduced.png`});assert.deepEqual(log.errors,[]);report.cases.push({name:'reduced instant band, static orbit and actor, explicit gate'});await context.close();console.log('PASS galaxy reduced');
 }
 {
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),log=observe(page);await page.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:get.call(this,type,...args);};});await open(page);await page.locator('[data-galaxy-band="1"]').click();await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.waitForFunction(()=>window.galaxyExperiment?.diagnostics().active);assert.equal((await state(frame,true)).band,1);assert.equal((await state(frame,true)).resources,null);await frame.locator('[data-galaxy-pause]').click();await frame.locator('canvas').focus();await page.keyboard.press('b');await page.keyboard.press('ArrowUp');await page.keyboard.press('+');await aligned(frame);const final=await snapshot(frame,true);assert.equal(final.band,0);assert.ok(final.targetTilt>.68&&final.targetZoom>1.15);await page.screenshot({path:`${output}/galaxy-no-webgl.png`});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await frame.waitForFunction(()=>!window.galaxyExperiment.diagnostics().active);await page.locator('.hero-copy .explore-button').click();await frame.waitForFunction(()=>window.galaxyExperiment.diagnostics().active);assert.deepEqual(await snapshot(frame,true),final);assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'no WebGL representative canvas, keyboard and exact handoff',final});await context.close();console.log('PASS galaxy no WebGL');
 }
 {
  const page=await browser.newPage(),log=observe(page),layouts=[];
  for(const viewport of [{width:1440,height:1000},{width:1280,height:900},{width:1366,height:768},{width:1280,height:720}]){await page.setViewportSize(viewport);await open(page);const layout=await page.evaluate(()=>{const copy=document.querySelector('.hero-copy').getBoundingClientRect(),dock=document.querySelector('.sound-dock').getBoundingClientRect(),header=document.querySelector('.studio-header').getBoundingClientRect();return{top:copy.top,bottom:copy.bottom,gap:dock.top-copy.bottom,header:header.bottom};});assert.ok(layout.gap>=12&&layout.top>layout.header,JSON.stringify({viewport,layout}));layouts.push({viewport,...layout});await page.screenshot({path:`${output}/galaxy-desktop-${viewport.width}-${viewport.height}.png`});}assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'desktop controls clear fixed sound dock',layouts});await page.close();console.log('PASS galaxy desktop dock clearance');
 }
}finally{fs.writeFileSync(`${output}/galaxy-audit.json`,JSON.stringify(report,null,2));await browser.close();await server.close();}console.log(JSON.stringify({base:report.base,cases:report.cases.length}));
