import fs from 'node:fs';
import assert from 'node:assert/strict';
import {startServer,launchBrowser,ready,settle,observe,output} from './browser-support.mjs';
const server=process.env.BASE_URL?{base:process.env.BASE_URL,close:async()=>{}}:await startServer(),browser=await launchBrowser(),report={base:server.base,cases:[]};
async function open(page){await page.goto(server.base+'/lab/glass.html');await ready(page);await settle(page);}
async function enter(page){await page.locator('.hero-copy .explore-button').click();const frame=await(await page.locator('.experiment-frame').elementHandle()).contentFrame();await frame.waitForURL(url=>url.searchParams.has('embedded'),{waitUntil:'domcontentloaded'});return frame;}
const snapshot=(target,embedded=false)=>target.evaluate(embedded=>(embedded?window.glassExperiment.state:window.studio.world.model.state).snapshot(),embedded);
async function difference(page,a,b){return page.evaluate(async([a,b])=>{const read=async data=>{const im=new Image();im.src='data:image/png;base64,'+data;await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);return ctx.getImageData(0,0,c.width,c.height).data;};const p=await read(a),q=await read(b);let changed=0,total=0;for(let i=0;i<p.length;i+=4){const d=Math.abs(p[i]-q[i])+Math.abs(p[i+1]-q[i+1])+Math.abs(p[i+2]-q[i+2]);if(d>9)changed++;total+=d;}return{changed,total};},[a.toString('base64'),b.toString('base64')]);}
try{
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
  const context=await browser.newContext({viewport,hasTouch:viewport.width<700}),page=await context.newPage(),log=observe(page);await open(page);await page.locator('[data-glass-action="ink"]').click();await page.locator('[data-glass-action="stamp"]').click();const start=await snapshot(page);const frame=await enter(page);await frame.waitForFunction(()=>window.glassExperiment?.diagnostics().active);await frame.waitForFunction(()=>window.glassExperiment.state.state.stampCount===1);assert.equal((await snapshot(frame,true)).ink,1);await page.evaluate(()=>document.querySelector('.experiment-frame').scrollIntoView({block:'center',behavior:'instant'}));
  const drag=await frame.locator('.glass-stage').boundingBox();await page.mouse.move(drag.x+drag.width*.25,drag.y+drag.height*.3);await page.mouse.down();await page.mouse.move(drag.x+drag.width*.7,drag.y+drag.height*.55,{steps:12});await page.mouse.up();assert.equal(await frame.evaluate(()=>getSelection().toString()),'');
  const button=frame.locator('.glass-note [data-glass-action="count"]'),box=await button.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.waitForTimeout(950);await frame.locator('[data-glass-freeze]').click();const hit=await button.evaluate(button=>{const b=button.getBoundingClientRect(),l=document.querySelector('.glass-main-lens').getBoundingClientRect(),x=b.x+b.width/2,y=b.y+b.height/2;return{buttonIsHit:document.elementFromPoint(x,y)===button,covered:Math.hypot(x-l.x-l.width/2,y-l.y-l.height/2)<l.width/2,pointerEvents:getComputedStyle(document.querySelector('.glass-main-lens')).pointerEvents};});assert.equal(hit.buttonIsHit,true);assert.equal(hit.covered,true);assert.equal(hit.pointerEvents,'none');await button.click();assert.equal((await snapshot(frame,true)).count,1);
  const filtered=await frame.locator('.glass-stage').screenshot({path:`${output}/glass-paper-${viewport.width}.png`});await frame.evaluate(()=>document.querySelectorAll('.lens').forEach(el=>{el.dataset.savedFilter=el.style.backdropFilter;el.style.backdropFilter='none';}));const clear=await frame.locator('.glass-stage').screenshot();const pixels=await difference(page,filtered,clear);assert.ok(pixels.changed>200&&pixels.total>5000,JSON.stringify(pixels));await frame.evaluate(()=>document.querySelectorAll('.lens').forEach(el=>el.style.backdropFilter=el.dataset.savedFilter));
  await frame.locator('.glass-stage').focus();await page.keyboard.press('ArrowLeft');await page.keyboard.press('ArrowUp');const prior=(await snapshot(frame,true)).stampCount;await page.keyboard.press('Space');await frame.waitForFunction(count=>window.glassExperiment.state.state.stampCount===count+1,prior);await page.keyboard.press('Home');await frame.waitForFunction(()=>{const s=window.glassExperiment.state.state;return s.x===0&&s.y===0;});
  if(viewport.width<700){const cdp=await context.newCDPSession(page),b=await frame.locator('.glass-stage').boundingBox(),p={x:b.x+b.width*.45,y:b.y+38};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...p,id:1}]});await frame.waitForFunction(()=>window.glassExperiment.diagnostics().pointer!==null);await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:p.x+30,y:p.y+20,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.equal(await frame.evaluate(()=>window.glassExperiment.diagnostics().pointer),null);await cdp.detach();}
  await frame.locator('[data-glass-freeze]').click();const exact=await snapshot(frame,true),maps=await frame.evaluate(()=>window.glassExperiment.diagnostics().maps);await page.screenshot({path:`${output}/glass-play-${viewport.width}.png`});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);assert.deepEqual(await snapshot(page),exact);await frame.waitForFunction(()=>!window.glassExperiment.diagnostics().active);const frames=await frame.evaluate(()=>window.glassExperiment.diagnostics().frames);await page.waitForTimeout(160);assert.equal(await frame.evaluate(()=>window.glassExperiment.diagnostics().frames),frames);
  for(let i=0;i<4;i++){await page.evaluate(()=>document.querySelector('.experiment-frame').scrollIntoView({block:'center',behavior:'instant'}));await page.waitForTimeout(45);await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(45);}await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);assert.deepEqual(await snapshot(page),exact);await page.screenshot({path:`${output}/glass-hero-${viewport.width}.png`});
  const contact=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,a=w.actor.root.getObjectByName('mote-right-hand').getWorldPosition(new T.Vector3()),b=w.model.grip.getWorldPosition(new T.Vector3());return a.distanceTo(b);});assert.ok(contact<1e-5,String(contact));
  const movingContact=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,m=w.model,s=m.snapshot(),samples=[];w.stop();m.setActive(false);for(const [vx,vy]of [[4,0],[0,4],[-3,2]]){m.restore({...s,frozen:false,vx,vy});w.frame(performance.now());const a=w.actor.root.getObjectByName('mote-right-hand').getWorldPosition(new T.Vector3()),b=m.grip.getWorldPosition(new T.Vector3()),scale=m.lenses[0].group.scale,uniform=m.lenses[0].material.uniforms.stretch.value;samples.push({distance:a.distanceTo(b),scale:[scale.x,scale.y],uniform:uniform.toArray()});}m.restore(s);m.setActive(true);w.frame(performance.now());w.start();return samples;});for(const sample of movingContact){assert.ok(sample.distance<1e-5,JSON.stringify(sample));assert.ok(Math.abs(sample.scale[0]*sample.scale[1]-1)<1e-9);assert.deepEqual(sample.uniform,sample.scale);}assert.ok(movingContact.some(sample=>sample.scale[0]!==1));
  const resources=await page.evaluate(()=>{const w=window.studio.world,m=w.model,before={...w.renderer.info.memory},texture=m.paper.texture,geometry=m.lenses[0].body.geometry;for(let i=0;i<30;i++){m.press('ink');m.press('count');m.update(0,{},0,100+i,true);w.composer.render();}return{before,after:{...w.renderer.info.memory},sameTexture:m.paper.texture===texture,sameGeometry:m.lenses[0].body.geometry===geometry};});assert.deepEqual(resources.after,resources.before);assert.equal(resources.sameTexture,true);assert.equal(resources.sameGeometry,true);
  await enter(page);await frame.waitForFunction(()=>window.glassExperiment.diagnostics().active);await page.evaluate(()=>document.querySelector('.hero-copy [data-glass-action="ink"]').click());await frame.waitForFunction(ink=>window.glassExperiment.state.state.ink===ink,(exact.ink+31)%3);assert.deepEqual(await frame.evaluate(()=>window.glassExperiment.diagnostics().maps),maps);
  const layout=await frame.evaluate(()=>{const rect=el=>{const r=el.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom};};return{stage:rect(document.querySelector('.glass-stage')),controls:rect(document.querySelector('.glass-controls')),notes:[...document.querySelectorAll('.glass-note')].map(rect),overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(layout.stage.bottom<=layout.controls.top);assert.equal(layout.overflow,0);assert.ok(layout.notes.every(n=>n.left>=layout.stage.left&&n.right<=layout.stage.right&&n.bottom<=layout.stage.bottom));
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);await page.evaluate(()=>{const m=window.studio.world.model;window.glassOld=m;window.glassDisposed={};for(const [name,o]of [['page',m.page],['large',m.lenses[0].body],['small',m.lenses[1].body]])for(const kind of ['geometry','material']){const key=name+kind;window.glassDisposed[key]=0;o[kind].addEventListener('dispose',()=>window.glassDisposed[key]++);}window.glassDisposed.texture=0;m.paper.texture.addEventListener('dispose',()=>window.glassDisposed.texture++);});await page.evaluate(()=>window.studio.router.navigate('/lab/'));await settle(page);const disposed=await page.evaluate(()=>({counts:window.glassDisposed,pick:window.glassOld.onPick}));assert.ok(Object.values(disposed.counts).every(n=>n===1));assert.equal(disposed.pick,null);assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({viewport,start,hit,pixels,contact,movingContact,resources,maps,layout,disposed});await context.close();console.log(`PASS glass live DOM, handoff and resources ${viewport.width}`);
 }
 {
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),log=observe(page);await open(page);
  const pixels=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,m=w.model,r=w.renderer;w.stop();const parent=m.root.parent,scene=new T.Scene(),camera=new T.PerspectiveCamera(42,1,.1,20);scene.background=new T.Color(0);camera.position.set(0,0,6);scene.add(m.root);const target=new T.WebGLRenderTarget(160,160),old=r.getRenderTarget(),values=m.lenses.map(l=>l.material.uniforms.power.value),buffers=[];r.setRenderTarget(target);for(const value of [0,1]){m.lenses.forEach(l=>l.material.uniforms.power.value=value);r.render(scene,camera);const data=new Uint8Array(160*160*4);r.readRenderTargetPixels(target,0,0,160,160,data);buffers.push(data);}r.setRenderTarget(old);target.dispose();parent.add(m.root);m.lenses.forEach((l,i)=>l.material.uniforms.power.value=values[i]);w.start();let changed=0,total=0;for(let i=0;i<buffers[0].length;i+=4){let d=0;for(let c=0;c<3;c++)d+=Math.abs(buffers[0][i+c]-buffers[1][i+c]);total+=d;if(d>5)changed++;}return{changed,total};});assert.ok(pixels.changed>100&&pixels.total>5000,JSON.stringify(pixels));
  await page.locator('.sound-toggle').click();await page.waitForFunction(()=>window.studio.score.audible);await page.evaluate(()=>{const m=window.studio.world.model,press=m.press.bind(m),complete=m.onComplete;m.press=(kind,options)=>{window.glassStart={time:window.studio.score.time,delay:options.wait||0,start:performance.now()};return press(kind,options);};m.onComplete=()=>{window.glassEnd=performance.now();complete();};});const hit=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,p=new T.Vector3(-.99,-.68,-.045).applyMatrix4(w.model.sheet.matrixWorld).project(w.camera);return{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2};});await page.mouse.click(hit.x,hit.y);await page.waitForFunction(()=>window.glassStart);await page.evaluate(()=>window.studio.score.context.suspend());await page.waitForFunction(()=>window.glassEnd);const timing=await page.evaluate(()=>({...window.glassStart,duration:(window.glassEnd-window.glassStart.start)/1000-window.glassStart.delay}));assert.ok(Math.abs((timing.time+timing.delay)*112/60*2-Math.round((timing.time+timing.delay)*112/60*2))<.04);assert.ok(Math.abs(timing.duration-60/112)<.13,JSON.stringify(timing));assert.deepEqual(log.errors,[]);report.cases.push({name:'real GPU lens, physical paper button and interrupted audio',pixels,timing});await page.close();console.log('PASS glass GPU and timing');
 }
 {
  const page=await browser.newPage(),log=observe(page),layouts=[];
  for(const viewport of [{width:320,height:568},{width:390,height:844},{width:768,height:1024},{width:844,height:390}]){await page.setViewportSize(viewport);await open(page);const result=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,m=w.model,p=new T.Vector3(),bottom=document.querySelector('.hero-copy').getBoundingClientRect().bottom;w.stop();m.setActive(false);let left=Infinity,right=-Infinity,top=Infinity;for(const x of [-1,0,1])for(const y of [-1,0,1]){const s=m.snapshot();m.restore({...s,x,y,targetX:x,targetY:y,power:1,targetPower:1});w.frame(performance.now());m.root.updateMatrixWorld(true);w.actor.root.updateMatrixWorld(true);for(const root of [m.root,w.actor.root])root.traverseVisible(o=>{if(!o.isMesh)return;const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){p.fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld).project(w.camera);left=Math.min(left,(p.x+1)*innerWidth/2);right=Math.max(right,(p.x+1)*innerWidth/2);top=Math.min(top,(1-p.y)*innerHeight/2);}});}return{left,right,gap:top-bottom,overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(result.left>=-.1&&result.right<=viewport.width+.1&&result.gap>8,JSON.stringify({viewport,result}));assert.equal(result.overflow,0);layouts.push({viewport,...result});}assert.deepEqual(log.errors,[]);report.cases.push({name:'compact paper and full lens travel',layouts});await page.close();console.log('PASS glass compact');
 }
 {
  const context=await browser.newContext({reducedMotion:'reduce'}),page=await context.newPage(),log=observe(page);await open(page);const first=await snapshot(page);await page.waitForTimeout(150);assert.deepEqual(await snapshot(page),first);await page.locator('[data-glass-action="stamp"]').click();assert.equal((await snapshot(page)).stampCount,1);const frame=await enter(page);await frame.locator('.experiment-gate button').waitFor();assert.equal(await frame.evaluate(()=>Boolean(window.glassExperiment)),false);await frame.locator('.experiment-gate button').click();await frame.waitForFunction(()=>window.glassExperiment?.diagnostics().active);await frame.locator('.glass-stage').focus();await page.keyboard.press('ArrowUp');await frame.waitForFunction(()=>{const s=window.glassExperiment.state.state;return s.y===s.targetY;});const exact=await snapshot(frame,true);await page.waitForTimeout(160);assert.deepEqual(await snapshot(frame,true),exact);assert.deepEqual(log.errors,[]);report.cases.push({name:'reduced immediate stamp and deliberate DOM experiment'});await context.close();console.log('PASS glass reduced');
 }
 {
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),log=observe(page);await page.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext,support=CSS.supports.bind(CSS);HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:get.call(this,type,...args);};CSS.supports=(property,value)=>property==='backdrop-filter'&&value?.startsWith('url(')?false:support(property,value);});await open(page);await page.locator('[data-glass-action="stamp"]').click();const frame=await enter(page);await frame.waitForFunction(()=>window.glassExperiment?.diagnostics().active);assert.equal(await frame.evaluate(()=>window.glassExperiment.diagnostics().refracts),false);assert.equal((await snapshot(frame,true)).stampCount,1);await frame.locator('.glass-note [data-glass-action="count"]').click();await frame.locator('.glass-stage').focus();await page.keyboard.press('ArrowUp');await page.keyboard.press('Space');await frame.waitForFunction(()=>window.glassExperiment.state.state.stampCount===2);await frame.locator('[data-glass-freeze]').click();const exact=await snapshot(frame,true);await page.screenshot({path:`${output}/glass-clear-fallback.png`});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await frame.waitForFunction(()=>!window.glassExperiment.diagnostics().active);await enter(page);await frame.waitForFunction(()=>window.glassExperiment.diagnostics().active);assert.deepEqual(await snapshot(frame,true),exact);assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'no WebGL and no SVG backdrop preserve live controls',exact});await context.close();console.log('PASS glass clear fallback');
 }
 {
  const page=await browser.newPage(),log=observe(page),layouts=[];
  for(const viewport of [{width:1440,height:1000},{width:1280,height:900},{width:1366,height:768},{width:1280,height:720}]){await page.setViewportSize(viewport);await open(page);const layout=await page.evaluate(()=>{const copy=document.querySelector('.hero-copy').getBoundingClientRect(),dock=document.querySelector('.sound-dock').getBoundingClientRect(),header=document.querySelector('.studio-header').getBoundingClientRect();return{top:copy.top,bottom:copy.bottom,dock:dock.top,header:header.bottom,gap:dock.top-copy.bottom};});await page.screenshot({path:`${output}/glass-desktop-${viewport.width}-${viewport.height}.png`});assert.ok(layout.gap>=12&&layout.top>layout.header,JSON.stringify({viewport,layout}));layouts.push({viewport,...layout});}assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'desktop controls clear fixed sound dock',layouts});await page.close();console.log('PASS glass desktop controls');
 }
}finally{fs.writeFileSync(`${output}/glass-audit.json`,JSON.stringify(report,null,2));await browser.close();await server.close();}console.log(JSON.stringify({base:report.base,cases:report.cases.length}));
