import fs from 'node:fs';
import assert from 'node:assert/strict';
import {startServer,launchBrowser,ready,settle,observe,output} from './browser-support.mjs';
const server=process.env.BASE_URL?{base:process.env.BASE_URL,close:async()=>{}}:await startServer(),browser=await launchBrowser(),report={base:server.base,cases:[]};
const frameOf=async page=>{const h=await page.locator('.experiment-frame').elementHandle(),frame=await h.contentFrame();await frame.waitForURL(url=>url.searchParams.has('embedded'),{waitUntil:'domcontentloaded'});return frame;};
try{
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
  const context=await browser.newContext({viewport,hasTouch:viewport.width<700}),page=await context.newPage(),log=observe(page);await page.goto(server.base+'/lab/moon.html');await ready(page);await settle(page);await page.screenshot({path:`${output}/moon-hero-${viewport.width}.png`});
  await page.locator('.sound-toggle').click();await page.waitForFunction(()=>window.studio.score.audible);await page.locator('.sound-toggle').click();const paused=await page.evaluate(()=>window.studio.score.time);
  await page.locator('[data-moon-launch]').focus();await page.keyboard.press('Space');await page.waitForFunction(()=>window.studio.world.model.diagnostics().elapsed>.65);const before=await page.evaluate(()=>window.studio.world.model.diagnostics());
  await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.waitForFunction(()=>window.moonExperiment?.diagnostics().active&&window.moonExperiment.diagnostics().mode==='descending');const after=await frame.evaluate(()=>window.moonExperiment.diagnostics());assert.ok(after.elapsed>=before.elapsed);assert.equal(await page.evaluate(()=>window.studio.world.model.diagnostics().active),false);
  await frame.waitForFunction(()=>window.moonExperiment.diagnostics().alive>10);await page.screenshot({path:`${output}/moon-dust-${viewport.width}.png`});
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);await frame.waitForFunction(()=>!window.moonExperiment.diagnostics().active);const offscreen=await frame.evaluate(()=>window.moonExperiment.diagnostics());await page.waitForTimeout(180);assert.equal(await frame.evaluate(()=>window.moonExperiment.diagnostics().frames),offscreen.frames);
  const resumed=await page.evaluate(()=>window.studio.world.model.diagnostics());assert.ok(resumed.elapsed>=after.elapsed);await page.waitForFunction(()=>window.studio.world.model.diagnostics().mode==='landed');assert.equal(await page.evaluate(()=>window.studio.score.time),paused);
  await page.locator('.hero-copy .explore-button').click();await frame.waitForFunction(()=>window.moonExperiment.diagnostics().active&&window.moonExperiment.diagnostics().mode==='landed');await frame.waitForFunction(()=>window.moonExperiment.diagnostics().elapsed>7.4&&window.moonExperiment.diagnostics().alive===0);await page.screenshot({path:`${output}/moon-landed-${viewport.width}.png`});
  const contacts=await frame.evaluate(async()=>{const T=await import('three'),{lunarHeight}=await import('/js/world/lunar-terrain.js'),m=window.moonExperiment;const feet=m.lander.footPositions.map(([x,y,z])=>{let lowest=Infinity;m.lander.root.updateMatrixWorld(true);m.lander.root.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position;for(let i=0;i<p.count;i++){const v=new T.Vector3().fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld);if(Math.hypot(v.x-x,v.z-z)<.49)lowest=Math.min(lowest,v.y);}});return{lowest,ground:lunarHeight(x,z)};});return{feet,state:m.diagnostics()};});for(const foot of contacts.feet)assert.ok(Math.abs(foot.lowest-foot.ground)<1e-5,JSON.stringify(foot));assert.equal(contacts.state.thrust,0);assert.equal(contacts.state.plume,false);assert.equal(contacts.state.alive,0);
  const flag=await frame.evaluate(()=>window.moonExperiment.effects.flag.children.map(o=>[...o.position.toArray(),...o.rotation.toArray()]));await page.waitForTimeout(200);assert.deepEqual(await frame.evaluate(()=>window.moonExperiment.effects.flag.children.map(o=>[...o.position.toArray(),...o.rotation.toArray()])),flag);
  await frame.locator('canvas').focus();const yaw=await frame.evaluate(()=>window.moonExperiment.diagnostics().yaw);await page.keyboard.press('ArrowRight');assert.ok(await frame.evaluate(y=>window.moonExperiment.diagnostics().yaw>y,yaw));await page.keyboard.press('Home');assert.equal(await frame.evaluate(()=>window.moonExperiment.diagnostics().yaw),.42);
  const canvas=await frame.locator('canvas').boundingBox();await page.mouse.move(canvas.x+canvas.width*.6,canvas.y+canvas.height*.6);await page.mouse.down();await page.mouse.move(canvas.x+canvas.width*.75,canvas.y+canvas.height*.58,{steps:4});await page.mouse.up();assert.equal(await frame.evaluate(()=>window.moonExperiment.diagnostics().drag),null);assert.notEqual(await frame.evaluate(()=>window.moonExperiment.diagnostics().yaw),.42);
  if(viewport.width<700){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:canvas.x+canvas.width*.5,y:canvas.y+canvas.height*.6,id:4}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await frame.waitForFunction(()=>window.moonExperiment.diagnostics().drag===null);await cdp.detach();}
  await frame.locator('#land-btn').click();assert.equal(await frame.evaluate(()=>window.moonExperiment.diagnostics().mode),'ready');await frame.locator('#land-btn').click();await frame.waitForFunction(()=>window.moonExperiment.diagnostics().mode==='landed');
  const resources=await frame.evaluate(()=>({memory:window.moonExperiment.diagnostics().resources,calls:window.moonExperiment.diagnostics().calls}));assert.deepEqual(resources.memory,contacts.state.resources);
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);await page.evaluate(()=>{const m=window.studio.world.model;window.moonOld=m;window.moonReleased={instance:0,geometry:0,material:0};m.terrain.stones.addEventListener('dispose',()=>window.moonReleased.instance++);m.effects.dust.geometry.addEventListener('dispose',()=>window.moonReleased.geometry++);m.effects.dust.material.addEventListener('dispose',()=>window.moonReleased.material++);});await page.evaluate(()=>window.studio.router.navigate('/lab/'));await settle(page);const disposed=await page.evaluate(()=>({counts:window.moonReleased,pick:window.moonOld.onPick}));assert.deepEqual(disposed,{counts:{instance:1,geometry:1,material:1},pick:null});assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);
  report.cases.push({viewport,before,after,resumed,contacts,resources,disposed});console.log(`PASS moon handoff, contact, controls, cleanup ${viewport.width}`);await context.close();
 }
 {
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),log=observe(page);await page.goto(server.base+'/lab/moon.html');await ready(page);await settle(page);await page.locator('.sound-toggle').click();await page.waitForFunction(()=>window.studio.score.audible);
  await page.evaluate(()=>{const score=window.studio.score,cue=score.cue.bind(score);score.cue=(name,delay=0)=>{if(name==='hover')window.moonCue={time:score.time,delay,start:performance.now()};cue(name,delay);};});
  await page.mouse.click(1420,120);assert.equal(await page.evaluate(()=>window.studio.world.model.diagnostics().mode),'ready');
  const hit=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world;w.model.root.updateMatrixWorld(true);const p=w.model.lander.root.localToWorld(new T.Vector3(0,1.9,1.7)).project(w.camera);return{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2};});await page.mouse.click(hit.x,hit.y);await page.waitForFunction(()=>window.studio.world.model.diagnostics().mode==='descending');const cue=await page.evaluate(()=>window.moonCue),halfBeat=(cue.time+cue.delay)*112/60*2;assert.ok(Math.abs(halfBeat-Math.round(halfBeat))<.04);
  await page.waitForTimeout(400);await page.evaluate(()=>window.studio.score.context.suspend());await page.waitForFunction(()=>window.studio.world.model.diagnostics().mode==='landed');const duration=await page.evaluate(()=>(performance.now()-window.moonCue.start)/1000-window.moonCue.delay);assert.ok(Math.abs(duration-12*60/112)<.35,JSON.stringify({duration}));assert.equal(await page.evaluate(()=>window.studio.score.audible),false);
  await page.locator('[data-moon-launch]').click();await page.locator('[data-moon-launch]').click();await page.waitForTimeout(200);await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.waitForFunction(()=>window.moonExperiment?.diagnostics().active);const before=await frame.evaluate(()=>window.moonExperiment.diagnostics().elapsed);
  for(let i=0;i<4;i++){await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(45);await page.evaluate(()=>document.querySelector('.experiment-frame').scrollIntoView({behavior:'instant',block:'center'}));await page.waitForTimeout(45);}
  await frame.waitForFunction(()=>window.moonExperiment.diagnostics().active);assert.ok(await frame.evaluate(before=>window.moonExperiment.diagnostics().elapsed>=before,before));await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);assert.ok(await page.evaluate(before=>window.studio.world.model.diagnostics().elapsed>=before,before));assert.deepEqual(log.errors,[]);report.cases.push({name:'physical hit, half beat, suspended audio, rapid ownership changes',cue,hit,duration});await page.close();console.log('PASS moon timing and ownership');
 }
 {
  const context=await browser.newContext(),page=await context.newPage(),log=observe(page),layouts=[];
  for(const viewport of [{width:320,height:568},{width:390,height:844},{width:768,height:1024},{width:844,height:390}]){await page.setViewportSize(viewport);await page.goto(server.base+'/lab/moon.html');await ready(page);await settle(page);
   const layout=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,m=w.model;w.stop();const now=performance.now(),bottom=document.querySelector('.hero-copy').getBoundingClientRect().bottom;let left=Infinity,right=-Infinity,top=Infinity;for(let i=0;i<80;i++){m.flight.restore({mode:'descending',elapsed:i/79*6.4285714286,delay:0});w.frame(now+i*16);const box=new T.Box3().setFromObject(m.root).union(new T.Box3().setFromObject(w.actor.root));for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const p=new T.Vector3(x,y,z).project(w.camera);left=Math.min(left,(p.x+1)*innerWidth/2);right=Math.max(right,(p.x+1)*innerWidth/2);top=Math.min(top,(1-p.y)*innerHeight/2);}}return{left,right,gap:top-bottom,scale:w.layoutScale,overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(layout.scale>.14,JSON.stringify(layout));assert.ok(layout.left>=-.1&&layout.right<=viewport.width+.1,JSON.stringify(layout));assert.ok(layout.gap>8,JSON.stringify(layout));assert.equal(layout.overflow,0);layouts.push({viewport,...layout});await page.screenshot({path:`${output}/moon-layout-${viewport.width}.png`});
  }assert.deepEqual(log.errors,[]);report.cases.push({name:'compact approach envelope',layouts});await context.close();console.log('PASS moon compact');
 }
 {
  const context=await browser.newContext({reducedMotion:'reduce'}),page=await context.newPage();await page.goto(server.base+'/lab/moon.html');await ready(page);await page.locator('[data-moon-launch]').click();await page.waitForFunction(()=>window.studio.world.model.diagnostics().mode==='landed');assert.equal(await page.evaluate(()=>window.studio.world.model.diagnostics().alive),0);await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.locator('.experiment-gate button').waitFor();assert.equal(await frame.evaluate(()=>Boolean(window.moonExperiment)),false);await frame.locator('.experiment-gate button').click();await frame.waitForFunction(()=>window.moonExperiment?.diagnostics().mode==='landed');const pose=()=>frame.evaluate(()=>{const values=[];window.moonExperiment.crew.root.traverse(o=>values.push([...o.position.toArray(),...o.quaternion.toArray(),...o.scale.toArray()]));return values;});const first=await pose();await page.waitForTimeout(200);assert.deepEqual(await pose(),first);report.cases.push({name:'reduced still landing and explicit experiment'});await context.close();console.log('PASS moon reduced');
 }
 {
  const context=await browser.newContext(),page=await context.newPage(),log=observe(page);await page.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:get.call(this,type,...args);};});await page.goto(server.base+'/lab/moon.html');await ready(page);assert.equal(await page.locator('[data-moon-launch]').isVisible(),false);await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.locator('.ocean-unavailable').waitFor();assert.equal(await frame.locator('#land-btn').isDisabled(),true);assert.deepEqual(log.errors,[]);report.cases.push({name:'no WebGL and navigation remain available'});await context.close();console.log('PASS moon no WebGL');
 }
}finally{fs.writeFileSync(`${output}/moon-audit.json`,JSON.stringify(report,null,2));await browser.close();await server.close();}console.log(JSON.stringify({base:report.base,cases:report.cases.length}));
