import fs from 'node:fs';
import assert from 'node:assert/strict';
import {startServer,launchBrowser,ready,settle,observe,output} from './browser-support.mjs';
const server=process.env.BASE_URL?{base:process.env.BASE_URL,close:async()=>{}}:await startServer(),browser=await launchBrowser(),report={base:server.base,cases:[]};
const still=page=>page.waitForFunction(()=>{const m=window.studio.world.model;return !m.diagnostics().pending&&!m.cloud.diagnostics().active;});
const write=async(page,text)=>{await page.locator('.hero-copy input[name="word-text"]').fill(text);await page.locator('.hero-copy input[name="word-text"]').press('Enter');};
const frameOf=async page=>{const h=await page.locator('.experiment-frame').elementHandle(),frame=await h.contentFrame();await frame.waitForURL(url=>url.searchParams.has('embedded'),{waitUntil:'domcontentloaded'});return frame;};
try{
 {
  const page=await browser.newPage();await page.goto(server.base+'/lab/partext.html');await ready(page);
  const springs=await page.evaluate(async()=>{const {createGlyphCloud,cleanWords}=await import('/js/world/glyph-cloud.js'),a=createGlyphCloud(1024),b=createGlyphCloud(1024);a.setText('换一句话');b.setText('换一句话');for(let i=0;i<12;i++)a.step(1/30);for(let i=0;i<48;i++)b.step(1/120);let positionError=0,velocityError=0;for(let i=0;i<a.positions.length;i++){positionError=Math.max(positionError,Math.abs(a.positions[i]-b.positions[i]));velocityError=Math.max(velocityError,Math.abs(a.velocities[i]-b.velocities[i]));}const unicode=cleanWords('👨‍👩‍👧‍👦'.repeat(13)),clusters=[...new Intl.Segmenter('zh',{granularity:'grapheme'}).segment(unicode)].length;for(const c of [a,b]){c.dispose();c.points.geometry.dispose();c.points.material.dispose();}return{positionError,velocityError,clusters};});assert.ok(springs.positionError<.00001);assert.ok(springs.velocityError<.00001);assert.equal(springs.clusters,12);report.cases.push({name:'time-step consistency and grapheme limit',...springs});await page.close();console.log('PASS partext spring and Unicode');
 }
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
  const context=await browser.newContext({viewport,hasTouch:viewport.width<700}),page=await context.newPage(),log=observe(page);await page.goto(server.base+'/lab/partext.html');await ready(page);await settle(page);await still(page);
  await page.evaluate(()=>{const c=window.studio.world.model.cloud;window.wordObjects={geometry:c.points.geometry,positions:c.positions,targets:c.targets,material:c.points.material};});
  await write(page,'灵感起航');await still(page);assert.equal(await page.evaluate(()=>window.studio.world.model.cloud.diagnostics().text),'灵感起航');
  await page.locator('.sound-toggle').click();await page.waitForFunction(()=>window.studio.score.audible);await page.locator('.sound-toggle').click();const paused=await page.evaluate(()=>window.studio.score.time);
  await write(page,'代码有光');await page.locator('.hero-copy [data-word-scatter]').focus();await page.keyboard.press('Space');await page.waitForFunction(()=>window.studio.world.model.cloud.diagnostics().active);await page.waitForTimeout(90);await page.screenshot({path:`${output}/partext-scatter-${viewport.width}.png`});await still(page);assert.equal(await page.evaluate(()=>window.studio.score.time),paused);assert.equal(await page.evaluate(()=>window.studio.world.model.cloud.diagnostics().text),'代码有光');
  const continuous=await page.evaluate(()=>{const m=window.studio.world.model,c=m.cloud;m.scatter({now:performance.now()/1000});m.update(0,{},0,performance.now()/1000+.06);const before=Array.from(c.positions),velocity=Array.from(c.velocities);m.setText('途中换句',{now:performance.now()/1000});let jump=0;for(let i=0;i<before.length;i++)jump=Math.max(jump,Math.abs(before[i]-c.positions[i]));return{jump,velocity:velocity.some(v=>Math.abs(v)>.01)};});assert.equal(continuous.jump,0);assert.equal(continuous.velocity,true);await still(page);
  await write(page,'   ');assert.equal(await page.evaluate(()=>window.studio.world.model.cloud.diagnostics().text),'途中换句');assert.match(await page.locator('.hero-copy .word-status').textContent(),/先写/);
  const composition=await page.evaluate(()=>{const form=document.querySelector('.hero-copy form'),input=form.querySelector('input'),before=window.studio.world.model.cloud.diagnostics().text;input.dispatchEvent(new CompositionEvent('compositionstart'));input.value='输入法组合';form.requestSubmit();const pending=window.studio.world.model.diagnostics().pending;input.dispatchEvent(new CompositionEvent('compositionend'));return{before,pending};});assert.equal(composition.pending,null);
  await page.locator('.hero-copy input').press('Enter');await still(page);assert.equal(await page.evaluate(()=>window.studio.world.model.cloud.diagnostics().text),'输入法组合');
  await write(page,'abcdefghijklmnop');await still(page);assert.equal(await page.locator('.hero-copy input').inputValue(),'abcdefghijkl');
  await page.locator('.sound-toggle').click();await page.waitForFunction(()=>window.studio.score.audible);await page.evaluate(()=>{const s=window.studio.score,cue=s.cue.bind(s);s.cue=(name,delay=0)=>{window.wordCue={time:s.time,delay};cue(name,delay);};});await write(page,'节拍排字');await still(page);const cue=await page.evaluate(()=>window.wordCue),beat=(cue.time+cue.delay)*112/60*2;assert.ok(Math.abs(beat-Math.round(beat))<.035);
  await page.evaluate(()=>window.studio.score.context.suspend());await write(page,'安静也有光');await still(page);assert.equal(await page.evaluate(()=>window.studio.score.audible),false);
  const hit=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,key=w.model.root.getObjectByName('word-scatter-key'),p=key.getWorldPosition(new T.Vector3()).project(w.camera);return{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2};});await page.mouse.click(hit.x,hit.y);await page.waitForFunction(()=>window.studio.world.model.cloud.diagnostics().active);await still(page);await page.mouse.click(viewport.width-8,120);assert.equal(await page.evaluate(()=>window.studio.world.model.cloud.diagnostics().active),false);
  await page.emulateMedia({reducedMotion:'reduce'});await write(page,'静止也清楚');await still(page);const reduced=await page.evaluate(()=>Array.from(window.studio.world.model.cloud.positions));await page.locator('.hero-copy [data-word-scatter]').click();await page.waitForTimeout(200);assert.deepEqual(await page.evaluate(()=>Array.from(window.studio.world.model.cloud.positions)),reduced);await page.emulateMedia({reducedMotion:'no-preference'});
  await write(page,'从这里出发');await still(page);await page.screenshot({path:`${output}/partext-words-${viewport.width}.png`});
  await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.waitForFunction(()=>window.wordExperiment?.diagnostics().text==='从这里出发'&&window.wordExperiment.diagnostics().frames>2);await frame.waitForFunction(()=>!window.wordExperiment.model.cloud.diagnostics().active);
  await frame.locator('input[name="word-text"]').fill('下一句在这里');await frame.locator('input[name="word-text"]').press('Enter');await frame.waitForFunction(()=>!window.wordExperiment.model.diagnostics().pending&&!window.wordExperiment.model.cloud.diagnostics().active);assert.equal(await page.locator('.hero-copy input').inputValue(),'下一句在这里');
  const projected=await frame.evaluate(async()=>{const T=await import('three'),box=document.querySelector('.word-canvas').getBoundingClientRect(),{camera,model}=window.wordExperiment,cloud=model.cloud;let i=0;while(i<cloud.positions.length&&Math.abs(cloud.positions[i])>.2)i+=3;const p=cloud.points.localToWorld(new T.Vector3(cloud.positions[i],cloud.positions[i+1],0)).project(camera);return{x:box.x+(p.x+1)*box.width/2,y:box.y+(1-p.y)*box.height/2};});
  const frameBox=await page.locator('.experiment-frame').boundingBox();await page.mouse.move(frameBox.x+projected.x,frameBox.y+projected.y);await frame.waitForFunction(()=>window.wordExperiment.diagnostics().pointer!==null);await page.waitForTimeout(350);const disturbed=await frame.evaluate(()=>window.wordExperiment.diagnostics());assert.ok(disturbed.cloud.error>.01);await page.mouse.move(4,100);await frame.waitForFunction(()=>window.wordExperiment.diagnostics().pointer===null&&!window.wordExperiment.model.cloud.diagnostics().active);
  if(viewport.width<700){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:frameBox.x+projected.x,y:frameBox.y+projected.y,id:1}]});await page.waitForTimeout(200);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await frame.waitForFunction(()=>window.wordExperiment.diagnostics().pointer===null);await cdp.detach();}
  await frame.locator('[data-word-next]').click();await frame.waitForFunction(()=>window.wordExperiment.diagnostics().text==='eli3xir'&&!window.wordExperiment.model.cloud.diagnostics().active);await page.screenshot({path:`${output}/partext-play-${viewport.width}.png`});
  const memory=await frame.evaluate(()=>{const m=window.wordExperiment.model,c=m.cloud,before=window.wordExperiment.diagnostics().resources,ids={g:c.points.geometry,p:c.positions};for(let i=0;i<24;i++){m.setText(i%2?'反复排字':'稳定光点',{reduced:true});m.scatter({reduced:true});}return{before,after:window.wordExperiment.diagnostics().resources,same:ids.g===c.points.geometry&&ids.p===c.positions};});assert.deepEqual(memory.before,memory.after);assert.equal(memory.same,true);
  await page.evaluate(()=>scrollTo(0,0));await frame.waitForFunction(()=>!window.wordExperiment.diagnostics().active);const hidden=await frame.evaluate(()=>window.wordExperiment.diagnostics().frames);await page.waitForTimeout(250);assert.equal(await frame.evaluate(()=>window.wordExperiment.diagnostics().frames),hidden);await still(page);
  const ownership=await page.evaluate(()=>{const c=window.studio.world.model.cloud,o=window.wordObjects;window.wordReleased=[0,0,0];window.studio.world.model.root.children.find(o=>o.isInstancedMesh).addEventListener('dispose',()=>window.wordReleased[2]++);c.points.geometry.addEventListener('dispose',()=>window.wordReleased[0]++);c.points.material.addEventListener('dispose',()=>window.wordReleased[1]++);window.oldWord=window.studio.world.model;return o.geometry===c.points.geometry&&o.positions===c.positions&&o.targets===c.targets&&o.material===c.points.material;});assert.equal(ownership,true);
  await page.evaluate(()=>window.studio.router.navigate('/lab/'));await settle(page);const released=await page.evaluate(()=>({counts:window.wordReleased,callback:window.oldWord.onPick,pending:window.oldWord.diagnostics().pending}));assert.deepEqual(released,{counts:[1,1,1],callback:null,pending:null});assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);
  report.cases.push({viewport,paused,continuous,composition,cue,hit,disturbed:disturbed.cloud,memory,hidden,released});console.log(`PASS partext ${viewport.width}`);await context.close();
 }
 {
  const context=await browser.newContext(),page=await context.newPage(),log=observe(page),layouts=[];for(const viewport of [{width:320,height:568},{width:390,height:844},{width:768,height:1024},{width:844,height:390}]){
   await page.setViewportSize(viewport);await page.goto(server.base+'/lab/partext.html');await ready(page);await settle(page);await still(page);
   const layout=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,m=w.model;w.stop();const now=performance.now(),bottom=document.querySelector('.hero-copy').getBoundingClientRect().bottom;let left=Infinity,right=-Infinity,top=Infinity;for(let step=0;step<80;step++){if(step%20===0)m.scatter({now:(now+step*30)/1000});w.frame(now+step*30);const box=new T.Box3().setFromObject(m.root).union(new T.Box3().setFromObject(w.actor.root));for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const p=new T.Vector3(x,y,z).project(w.camera);left=Math.min(left,(p.x+1)*innerWidth/2);right=Math.max(right,(p.x+1)*innerWidth/2);top=Math.min(top,(1-p.y)*innerHeight/2);}}return{left,right,gap:top-bottom,overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(layout.left>=-.1&&layout.right<=viewport.width+.1,JSON.stringify(layout));assert.ok(layout.gap>8,JSON.stringify(layout));assert.equal(layout.overflow,0);await page.screenshot({path:`${output}/partext-layout-${viewport.width}.png`});layouts.push({viewport,...layout});
  }assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'compact scatter envelope',layouts});await context.close();console.log('PASS partext compact');
 }
 {
  const context=await browser.newContext({reducedMotion:'reduce'}),page=await context.newPage();await page.goto(server.base+'/lab/partext.html');await ready(page);await write(page,'准备好再开始');await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.locator('.experiment-gate button').waitFor();assert.equal(await frame.evaluate(()=>Boolean(window.wordExperiment)),false);await frame.locator('.experiment-gate button').click();await frame.waitForFunction(()=>window.wordExperiment?.diagnostics().text==='准备好再开始');assert.equal(await frame.evaluate(()=>window.wordExperiment.model.cloud.diagnostics().active),false);const pose=()=>frame.evaluate(()=>{const result=[];window.wordExperiment.actor.root.traverse(o=>result.push([...o.position.toArray(),...o.quaternion.toArray(),...o.scale.toArray()]));return result;});const initialPose=await pose();await page.waitForTimeout(250);assert.deepEqual(await pose(),initialPose);report.cases.push({name:'reduced explicit start, selected words and static actor'});await context.close();console.log('PASS partext reduced');
 }
 {
  const context=await browser.newContext(),page=await context.newPage(),log=observe(page);await page.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:get.call(this,type,...args);};});await page.goto(server.base+'/lab/partext.html');await ready(page);await write(page,'文字依然可读');assert.equal(await page.locator('.hero-copy [data-word-scatter]').isVisible(),false);await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.locator('.word-unavailable').waitFor();await frame.waitForFunction(()=>window.wordExperiment?.diagnostics().text==='文字依然可读');await frame.locator('[data-word-next]').click();assert.equal(await page.locator('.hero-copy input').inputValue(),'eli3xir');assert.deepEqual(log.errors,[]);report.cases.push({name:'no WebGL text controls and handoff'});await context.close();console.log('PASS partext no WebGL');
 }
}finally{fs.writeFileSync(`${output}/partext-audit.json`,JSON.stringify(report,null,2));await browser.close();await server.close();}console.log(JSON.stringify({base:report.base,cases:report.cases.length}));
