import fs from 'node:fs';
import assert from 'node:assert/strict';
import {startServer,launchBrowser,ready,settle,observe,output} from './browser-support.mjs';
const server=process.env.BASE_URL?{base:process.env.BASE_URL,close:async()=>{}}:await startServer(),browser=await launchBrowser(),report={base:server.base,cases:[]};
async function open(page){await page.goto(server.base+'/lab/trails.html');await ready(page);await settle(page);}
async function frameOf(page){const frame=await(await page.locator('.experiment-frame').elementHandle()).contentFrame();await frame.waitForURL(url=>url.searchParams.has('embedded'),{waitUntil:'domcontentloaded'});return frame;}
const state=(target,embedded=false)=>target.evaluate(embedded=>embedded?window.trailsExperiment.diagnostics():window.studio.world.model.diagnostics(),embedded);
const photo=s=>Object.fromEntries(['hours','recorded','start','elapsed','delay','mode','pole','target','paused'].map(key=>[key,s[key]]));
const pose=target=>target.evaluate(()=>{const values=[];window.trailsExperiment.actor.root.traverse(o=>values.push([...o.position.toArray(),...o.quaternion.toArray(),...o.scale.toArray()]));return values;});
try{
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
  const context=await browser.newContext({viewport,hasTouch:viewport.width<700}),page=await context.newPage(),log=observe(page);await open(page);
  await page.locator('[data-exposure="6"]').click();await page.locator('[data-trails-launch]').click();await page.waitForTimeout(850);await page.locator('[data-trails-pause]').click();const paused=await state(page);await page.waitForTimeout(160);assert.deepEqual(photo(await state(page)),photo(paused));await page.screenshot({path:`${output}/trails-hero-${viewport.width}.png`});
  await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.waitForFunction(()=>window.trailsExperiment?.diagnostics().active);const after=await state(frame,true);assert.deepEqual(photo(after),photo(paused));assert.equal((await state(page)).active,false);
  await page.evaluate(()=>document.querySelector('.experiment-frame').scrollIntoView({block:'center',behavior:'instant'}));await frame.locator('canvas').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowUp');await frame.waitForFunction(()=>window.trailsExperiment.diagnostics().pole.every((v,i)=>v===window.trailsExperiment.diagnostics().target[i]));const aimed=await state(frame,true);assert.deepEqual(aimed.target,[.1,.1]);
  const box=await frame.locator('canvas').boundingBox();const origin={x:box.x+box.width*.5,y:box.y+box.height*.4};await page.mouse.move(origin.x,origin.y);await page.mouse.down();await frame.waitForFunction(()=>window.trailsExperiment.diagnostics().drag!==null);await page.mouse.move(origin.x+box.width*.06,origin.y+box.height*.04,{steps:8});await page.mouse.up();assert.equal((await state(frame,true)).drag,null);assert.notDeepEqual((await state(frame,true)).target,aimed.target);
  if(viewport.width<700){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...origin,id:4}]});await frame.waitForFunction(()=>window.trailsExperiment.diagnostics().drag!==null);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await frame.waitForFunction(()=>window.trailsExperiment.diagnostics().drag===null);await cdp.detach();}
  await frame.locator('canvas').focus();await page.keyboard.press('Home');await frame.waitForFunction(()=>window.trailsExperiment.diagnostics().pole.every(v=>v===0));await frame.locator('[data-trails-pause]').click();await frame.waitForFunction(()=>window.trailsExperiment.diagnostics().mode==='complete');const completed=await state(frame,true);assert.equal(completed.recorded,6);assert.ok(Math.abs(completed.angle-Math.PI*2*6/23.9345)<1e-12);await page.screenshot({path:`${output}/trails-complete-${viewport.width}.png`});
  // The first visible meteor uploads one geometry. Warm before checking for growth.
  const memory=await frame.evaluate(()=>({...window.trailsExperiment.renderer.info.memory}));await frame.evaluate(()=>{const m=window.trailsExperiment.model,original=m.snapshot();for(let i=0;i<24;i++){m.exposure.reset();m.exposure.launch({reduced:true});m.update(0,{},0,100+i);window.trailsExperiment.renderer.render(m.root.parent,window.trailsExperiment.camera);}m.restore(original);});assert.deepEqual(await frame.evaluate(()=>({...window.trailsExperiment.renderer.info.memory})),memory);
  await frame.locator('[data-exposure="1"]').click();assert.equal((await state(frame,true)).recorded,6);const selected=await state(frame,true);await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);assert.deepEqual(photo(await state(page)),photo(selected));await frame.waitForFunction(()=>!window.trailsExperiment.diagnostics().active);const stopped=(await state(frame,true)).frames;await page.waitForTimeout(180);assert.equal((await state(frame,true)).frames,stopped);
  for(let i=0;i<4;i++){await page.evaluate(()=>document.querySelector('.experiment-frame').scrollIntoView({block:'center',behavior:'instant'}));await page.waitForTimeout(45);await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(45);}await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);assert.deepEqual(photo(await state(page)),photo(selected));
  await page.locator('.hero-copy .explore-button').click();await frame.waitForFunction(()=>window.trailsExperiment.diagnostics().active);await page.evaluate(()=>document.querySelector('.hero-copy [data-trails-launch]').click());await frame.waitForFunction(()=>window.trailsExperiment.diagnostics().mode==='exposing');assert.equal((await state(frame,true)).hours,1);await frame.locator('[data-trails-reset]').click();assert.equal((await state(frame,true)).recorded,0);
  const layout=await frame.evaluate(async()=>{const c=document.querySelector('canvas').getBoundingClientRect(),h=document.querySelector('.demo-hud').getBoundingClientRect(),f=document.querySelector('.trails-controls').getBoundingClientRect(),T=await import('three'),e=window.trailsExperiment,p=new T.Vector3();let x=0,y=0;e.model.root.updateMatrixWorld(true);e.model.root.traverseVisible(o=>{if(!o.isMesh||o===e.model.field.trails)return;const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){p.fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld).project(e.camera);x=Math.max(x,Math.abs(p.x));y=Math.max(y,Math.abs(p.y));}});for(const s of e.model.field.stars){p.set(s.r*Math.cos(s.angle),s.r*Math.sin(s.angle),s.z).multiplyScalar(1.42).applyMatrix4(e.model.field.root.matrixWorld).project(e.camera);x=Math.max(x,Math.abs(p.x));y=Math.max(y,Math.abs(p.y));}return{canvasTop:c.top,canvasBottom:c.bottom,hudBottom:h.bottom,controlsTop:f.top,overflow:document.documentElement.scrollWidth-innerWidth,envelope:{x,y}};});assert.ok(layout.canvasTop>=layout.hudBottom&&layout.canvasBottom<=layout.controlsTop,JSON.stringify(layout));assert.ok(layout.envelope.x<1&&layout.envelope.y<1,JSON.stringify(layout));assert.equal(layout.overflow,0);
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>window.studio.world.model.diagnostics().active);await page.evaluate(()=>{const m=window.studio.world.model;window.trailsOld=m;window.trailsDisposed={};for(const [name,item] of [['trails',m.field.trails],['stars',m.field.points],['meteor',m.field.meteor]])for(const type of ['geometry','material']){const key=name+type;window.trailsDisposed[key]=0;item[type].addEventListener('dispose',()=>window.trailsDisposed[key]++);}});await page.evaluate(()=>window.studio.router.navigate('/lab/'));await settle(page);const disposed=await page.evaluate(()=>({counts:window.trailsDisposed,pick:window.trailsOld.onPick}));assert.ok(Object.values(disposed.counts).every(n=>n===1));assert.equal(disposed.pick,null);assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);
  report.cases.push({viewport,paused,after,completed,layout,memory,disposed});await context.close();console.log(`PASS trails state, input, ownership and resources ${viewport.width}`);
 }
 {
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),log=observe(page);await open(page);
  const projection=await page.evaluate(async()=>{const T=await import('three'),{createStarField}=await import('/js/world/star-field.js'),{rotateStar}=await import('/js/world/star-exposure.js'),{disposeGroup}=await import('/js/world/materials.js'),w=window.studio.world,r=w.renderer;w.stop();const field=createStarField(1),scene=new T.Scene(),camera=new T.OrthographicCamera(-1.6,1.6,1.6,-1.6,.1,10);camera.position.z=4;camera.updateMatrixWorld();scene.add(field.root);field.trails.visible=false;field.points.geometry.attributes.aTint.setW(0,6);field.points.onBeforeRender=()=>field.uniforms.viewport.value.set(1024,1024);const target=new T.WebGLRenderTarget(256,256),pixels=new Uint8Array(256*256*4),oldTarget=r.getRenderTarget(),oldColor=r.getClearColor(new T.Color()).clone(),oldAlpha=r.getClearAlpha(),checks=[];r.setClearColor(0,1);r.setRenderTarget(target);
   for(const [start,angle,pole] of [[0,0,[0,0]],[.2,.7,[.65,-.4]],[.8,1.2,[-.6,.4]]]){field.update({start,angle,pole,progress:0});r.render(scene,camera);r.readRenderTargetPixels(target,0,0,256,256,pixels);let sum=0,x=0,y=0;for(let i=0;i<256*256;i++){const v=pixels[i*4]+pixels[i*4+1]+pixels[i*4+2];sum+=v;x+=(i%256+.5)*v;y+=(Math.floor(i/256)+.5)*v;}const p=new T.Vector3(...rotateStar(field.stars[0],start+angle,pole)).multiplyScalar(1.42).project(camera),expected=[(p.x+1)*128,(p.y+1)*128],actual=[x/sum,y/sum];checks.push({expected,actual,error:Math.hypot(actual[0]-expected[0],actual[1]-expected[1]),sum});}
   r.setRenderTarget(oldTarget);r.setClearColor(oldColor,oldAlpha);target.dispose();disposeGroup(field.root);w.start();return checks;});assert.ok(projection.every(p=>p.sum>0&&p.error<1),JSON.stringify(projection));
  await page.locator('.sound-toggle').click();await page.waitForFunction(()=>window.studio.score.audible);await page.evaluate(()=>{const m=window.studio.world.model,launch=m.launch.bind(m),done=m.onComplete;m.launch=options=>{window.trailsStart={time:window.studio.score.time,delay:options.wait||0,start:performance.now()};return launch(options);};m.onComplete=()=>{window.trailsEnd=performance.now();done();};});await page.mouse.click(1410,120);assert.equal((await state(page)).mode,'ready');const hit=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,p=w.model.device.cameraRig.localToWorld(new T.Vector3(0,0,-.17)).project(w.camera);return{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2};});await page.mouse.click(hit.x,hit.y);await page.waitForFunction(()=>window.trailsStart);await page.evaluate(()=>window.studio.score.context.suspend());await page.waitForFunction(()=>window.trailsEnd);const timing=await page.evaluate(()=>({...window.trailsStart,duration:(window.trailsEnd-window.trailsStart.start)/1000-window.trailsStart.delay}));assert.ok(Math.abs((timing.time+timing.delay)*112/60*2-Math.round((timing.time+timing.delay)*112/60*2))<.04);assert.ok(Math.abs(timing.duration-8*60/112)<.13,JSON.stringify(timing));assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'actual GPU projection, physical shutter and audio interruption',projection,timing});await page.close();console.log('PASS trails projection and timing');
 }
 {
  const page=await browser.newPage(),log=observe(page),layouts=[];
  for(const viewport of [{width:320,height:568},{width:390,height:844},{width:768,height:1024},{width:844,height:390}]){await page.setViewportSize(viewport);await open(page);const layout=await page.evaluate(async()=>{const T=await import('three'),w=window.studio.world,m=w.model;w.stop();const now=performance.now(),bottom=document.querySelector('.hero-copy').getBoundingClientRect().bottom;let left=Infinity,right=-Infinity,top=Infinity;for(let i=0;i<24;i++){m.exposure.select(6);m.exposure.launch({reduced:true});m.exposure.aim(i%2?.85:-.85,i%3?.7:-.7);m.exposure.update(0,true);w.frame(now+i*20);const box=m.layoutBounds.clone().applyMatrix4(m.root.matrixWorld).union(new T.Box3().setFromObject(w.actor.root));for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const p=new T.Vector3(x,y,z).project(w.camera);left=Math.min(left,(p.x+1)*innerWidth/2);right=Math.max(right,(p.x+1)*innerWidth/2);top=Math.min(top,(1-p.y)*innerHeight/2);}}return{left,right,gap:top-bottom,scale:w.layoutScale,overflow:document.documentElement.scrollWidth-innerWidth};});assert.ok(layout.left>=-.1&&layout.right<=viewport.width+.1&&layout.gap>8,JSON.stringify(layout));assert.equal(layout.overflow,0);layouts.push({viewport,...layout});await page.screenshot({path:`${output}/trails-layout-${viewport.width}.png`});}assert.deepEqual(log.errors,[]);report.cases.push({name:'four compact exposure envelopes',layouts});await page.close();console.log('PASS trails compact');
 }
 {
  const context=await browser.newContext({reducedMotion:'reduce'}),page=await context.newPage(),log=observe(page);await open(page);assert.equal((await state(page)).mode,'ready');await page.locator('[data-trails-launch]').click();assert.equal((await state(page)).mode,'complete');const fixed=photo(await state(page));await page.waitForTimeout(220);assert.deepEqual(photo(await state(page)),fixed);await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.locator('.experiment-gate button').waitFor();assert.equal(await frame.evaluate(()=>Boolean(window.trailsExperiment)),false);await frame.locator('.experiment-gate button').click();await frame.waitForFunction(()=>window.trailsExperiment?.diagnostics().active);await frame.locator('[data-trails-launch]').click();assert.equal((await state(frame,true)).mode,'complete');const still=await pose(frame);await page.waitForTimeout(220);assert.deepEqual(await pose(frame),still);await page.screenshot({path:`${output}/trails-reduced.png`});assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'reduced instant exposure, explicit gate, still actor'});await context.close();console.log('PASS trails reduced');
 }
 {
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),log=observe(page);await page.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:get.call(this,type,...args);};});await open(page);await page.locator('[data-exposure="6"]').click();await page.locator('[data-trails-launch]').click();assert.match(await page.locator('.hero-copy .trails-status').textContent(),/6 小时/);await page.locator('.hero-copy .explore-button').click();const frame=await frameOf(page);await frame.waitForFunction(()=>window.trailsExperiment?.diagnostics().active);assert.equal((await state(frame,true)).recorded,6);assert.equal((await state(frame,true)).resources,null);await frame.locator('[data-trails-reset]').click();await frame.locator('canvas').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Space');await frame.waitForFunction(()=>window.trailsExperiment.diagnostics().mode==='complete');const final=await state(frame,true);assert.equal(final.recorded,6);assert.deepEqual(final.target,[.1,0]);assert.ok(final.frames>20);await page.screenshot({path:`${output}/trails-no-webgl.png`});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForFunction(()=>document.querySelector('.hero-copy .trails-status').textContent.includes('6 小时'));await frame.waitForFunction(()=>!window.trailsExperiment.diagnostics().active);const stopped=(await state(frame,true)).frames;await page.waitForTimeout(200);assert.equal((await state(frame,true)).frames,stopped);assert.deepEqual(log.errors,[]);assert.deepEqual(log.failed,[]);report.cases.push({name:'no WebGL canvas, keyboard, handoff and offscreen',final});await context.close();console.log('PASS trails no WebGL');
 }
}finally{fs.writeFileSync(`${output}/trails-audit.json`,JSON.stringify(report,null,2));await browser.close();await server.close();}console.log(JSON.stringify({base:report.base,cases:report.cases.length}));
