const clamp=(value,lo,hi)=>Math.max(lo,Math.min(hi,value));
const duration=60/112;
export const GLASS_INKS=['#ad5949','#367f82','#746d9f'];
export function createGlassState(){
 const s={x:0,y:0,vx:0,vy:0,targetX:0,targetY:0,power:.65,targetPower:.65,stamped:false,stampCount:0,ink:0,count:0,stampElapsed:duration,stampDelay:0,stampQueued:false,frozen:false};
 return{state:s,move(x,y){if(Number.isFinite(x)&&Number.isFinite(y)){s.targetX=clamp(x,-1,1);s.targetY=clamp(y,-1,1);}},focus(value){if(Number.isFinite(value))s.targetPower=clamp(value,0,1);},freeze(value){s.frozen=Boolean(value);},
  press(kind,{wait=0,reduced=false}={}){if(kind==='ink')s.ink=(s.ink+1)%GLASS_INKS.length;else if(kind==='count')s.count=Math.min(999,s.count+1);else if(kind==='stamp'){if(reduced){s.stamped=true;s.stampCount=Math.min(999,s.stampCount+1);s.stampElapsed=duration;s.stampDelay=0;s.stampQueued=false;return true;}if(s.stampElapsed<duration){s.stampQueued=true;return false;}s.stampElapsed=0;s.stampDelay=clamp(Number(wait)||0,0,1);}return false;},
  update(dt,reduced=false){if(!Number.isFinite(dt)||dt<0)return false;let completed=false;
   if(reduced){s.x=s.targetX;s.y=s.targetY;s.vx=s.vy=0;s.power=s.targetPower;}else{if(!s.frozen)for(const [key,velocity,target]of [['x','vx','targetX'],['y','vy','targetY']]){const offset=s[key]-s[target],v=s[velocity]+10*offset,e=Math.exp(-10*dt);s[key]=s[target]+(offset+v*dt)*e;s[velocity]=(s[velocity]-10*v*dt)*e;if(Math.abs(s[key]-s[target])+Math.abs(s[velocity])<1e-5){s[key]=s[target];s[velocity]=0;}}s.power+=(s.targetPower-s.power)*(1-Math.exp(-dt*9));if(Math.abs(s.targetPower-s.power)<1e-5)s.power=s.targetPower;}
   if(s.stampElapsed<duration){const used=Math.min(s.stampDelay,dt);s.stampDelay-=used;const remaining=dt-used;s.stampElapsed=Math.min(duration,s.stampElapsed+(reduced?duration:remaining));if(s.stampElapsed===duration){s.stamped=true;s.stampCount=Math.min(999,s.stampCount+1);completed=true;if(s.stampQueued&&!reduced){s.stampQueued=false;s.stampElapsed=0;}}}return completed;
  },snapshot(){return{...s};},restore(value){if(!value||typeof value!=='object')return false;const numbers=['x','y','vx','vy','targetX','targetY','power','targetPower','ink','count','stampCount','stampElapsed','stampDelay'];if(numbers.some(key=>!Number.isFinite(value[key]))||['stamped','stampQueued','frozen'].some(key=>typeof value[key]!=='boolean'))return false;for(const key of numbers)s[key]=value[key];for(const key of ['stamped','stampQueued','frozen'])s[key]=value[key];for(const key of ['x','y','targetX','targetY'])s[key]=clamp(s[key],-1,1);s.vx=clamp(s.vx,-20,20);s.vy=clamp(s.vy,-20,20);s.power=clamp(s.power,0,1);s.targetPower=clamp(s.targetPower,0,1);s.ink=clamp(Math.round(s.ink),0,2);s.count=clamp(Math.round(s.count),0,999);s.stampCount=clamp(Math.round(s.stampCount),0,999);s.stampElapsed=clamp(s.stampElapsed,0,duration);s.stampDelay=clamp(s.stampDelay,0,1);return true;},get progress(){return s.stampElapsed/duration;}};
}
